export interface Country {
  name: string;
  code: string;
  dialCode: string;
  format: string;
}

export const countries: Country[] = [
  { name: "Afghanistan", code: "AF", dialCode: "+93", format: "+93 XX XXX XXXX" },
  { name: "Albania", code: "AL", dialCode: "+355", format: "+355 XX XXX XXXX" },
  { name: "Algeria", code: "DZ", dialCode: "+213", format: "+213 XXX XX XX XX" },
  { name: "Andorra", code: "AD", dialCode: "+376", format: "+376 XXX XXX" },
  { name: "Angola", code: "AO", dialCode: "+244", format: "+244 XXX XXX XXX" },
  { name: "Antigua and Barbuda", code: "AG", dialCode: "+1-268", format: "+1 268 XXX XXXX" },
  { name: "Argentina", code: "AR", dialCode: "+54", format: "+54 XX XXXX XXXX" },
  { name: "Armenia", code: "AM", dialCode: "+374", format: "+374 XX XXX XXX" },
  { name: "Australia", code: "AU", dialCode: "+61", format: "+61 X XXXX XXXX" },
  { name: "Austria", code: "AT", dialCode: "+43", format: "+43 XXX XXXXXXX" },
  { name: "Azerbaijan", code: "AZ", dialCode: "+994", format: "+994 XX XXX XX XX" },
  { name: "Bahamas", code: "BS", dialCode: "+1-242", format: "+1 242 XXX XXXX" },
  { name: "Bahrain", code: "BH", dialCode: "+973", format: "+973 XXXX XXXX" },
  { name: "Bangladesh", code: "BD", dialCode: "+880", format: "+880 XXXX XXXXXX" },
  { name: "Barbados", code: "BB", dialCode: "+1-246", format: "+1 246 XXX XXXX" },
  { name: "Belarus", code: "BY", dialCode: "+375", format: "+375 XX XXX XX XX" },
  { name: "Belgium", code: "BE", dialCode: "+32", format: "+32 XXX XX XX XX" },
  { name: "Belize", code: "BZ", dialCode: "+501", format: "+501 XXX XXXX" },
  { name: "Benin", code: "BJ", dialCode: "+229", format: "+229 XX XX XX XX" },
  { name: "Bhutan", code: "BT", dialCode: "+975", format: "+975 XX XXX XXX" },
  { name: "Bolivia", code: "BO", dialCode: "+591", format: "+591 X XXX XXXX" },
  { name: "Bosnia and Herzegovina", code: "BA", dialCode: "+387", format: "+387 XX XXX XXX" },
  { name: "Botswana", code: "BW", dialCode: "+267", format: "+267 XX XXX XXX" },
  { name: "Brazil", code: "BR", dialCode: "+55", format: "+55 XX XXXXX XXXX" },
  { name: "Brunei", code: "BN", dialCode: "+673", format: "+673 XXX XXXX" },
  { name: "Bulgaria", code: "BG", dialCode: "+359", format: "+359 XX XXX XXXX" },
  { name: "Burkina Faso", code: "BF", dialCode: "+226", format: "+226 XX XX XX XX" },
  { name: "Burundi", code: "BI", dialCode: "+257", format: "+257 XX XX XXXX" },
  { name: "Cambodia", code: "KH", dialCode: "+855", format: "+855 XX XXX XXX" },
  { name: "Cameroon", code: "CM", dialCode: "+237", format: "+237 X XXXX XXXX" },
  { name: "Canada", code: "CA", dialCode: "+1", format: "+1 XXX XXX XXXX" },
  { name: "Cape Verde", code: "CV", dialCode: "+238", format: "+238 XXX XX XX" },
  { name: "Central African Republic", code: "CF", dialCode: "+236", format: "+236 XX XX XX XX" },
  { name: "Chad", code: "TD", dialCode: "+235", format: "+235 XX XX XX XX" },
  { name: "Chile", code: "CL", dialCode: "+56", format: "+56 X XXXX XXXX" },
  { name: "China", code: "CN", dialCode: "+86", format: "+86 XXX XXXX XXXX" },
  { name: "Colombia", code: "CO", dialCode: "+57", format: "+57 XXX XXX XXXX" },
  { name: "Comoros", code: "KM", dialCode: "+269", format: "+269 XXX XX XX" },
  { name: "Congo (DRC)", code: "CD", dialCode: "+243", format: "+243 XX XXX XXXX" },
  { name: "Congo (Republic)", code: "CG", dialCode: "+242", format: "+242 XX XXX XXXX" },
  { name: "Costa Rica", code: "CR", dialCode: "+506", format: "+506 XXXX XXXX" },
  { name: "Croatia", code: "HR", dialCode: "+385", format: "+385 XX XXX XXXX" },
  { name: "Cuba", code: "CU", dialCode: "+53", format: "+53 X XXX XXXX" },
  { name: "Cyprus", code: "CY", dialCode: "+357", format: "+357 XX XXX XXX" },
  { name: "Czech Republic", code: "CZ", dialCode: "+420", format: "+420 XXX XXX XXX" },
  { name: "Denmark", code: "DK", dialCode: "+45", format: "+45 XX XX XX XX" },
  { name: "Djibouti", code: "DJ", dialCode: "+253", format: "+253 XX XX XX XX" },
  { name: "Dominica", code: "DM", dialCode: "+1-767", format: "+1 767 XXX XXXX" },
  { name: "Dominican Republic", code: "DO", dialCode: "+1-809", format: "+1 809 XXX XXXX" },
  { name: "Ecuador", code: "EC", dialCode: "+593", format: "+593 XX XXX XXXX" },
  { name: "Egypt", code: "EG", dialCode: "+20", format: "+20 XX XXXX XXXX" },
  { name: "El Salvador", code: "SV", dialCode: "+503", format: "+503 XXXX XXXX" },
  { name: "Equatorial Guinea", code: "GQ", dialCode: "+240", format: "+240 XXX XXX XXX" },
  { name: "Eritrea", code: "ER", dialCode: "+291", format: "+291 X XXX XXX" },
  { name: "Estonia", code: "EE", dialCode: "+372", format: "+372 XXXX XXXX" },
  { name: "Eswatini", code: "SZ", dialCode: "+268", format: "+268 XXXX XXXX" },
  { name: "Ethiopia", code: "ET", dialCode: "+251", format: "+251 XX XXX XXXX" },
  { name: "Fiji", code: "FJ", dialCode: "+679", format: "+679 XXX XXXX" },
  { name: "Finland", code: "FI", dialCode: "+358", format: "+358 XX XXX XXXX" },
  { name: "France", code: "FR", dialCode: "+33", format: "+33 X XX XX XX XX" },
  { name: "Gabon", code: "GA", dialCode: "+241", format: "+241 X XX XX XX" },
  { name: "Gambia", code: "GM", dialCode: "+220", format: "+220 XXX XXXX" },
  { name: "Georgia", code: "GE", dialCode: "+995", format: "+995 XXX XX XX XX" },
  { name: "Germany", code: "DE", dialCode: "+49", format: "+49 XXX XXXXXXXX" },
  { name: "Ghana", code: "GH", dialCode: "+233", format: "+233 XX XXX XXXX" },
  { name: "Greece", code: "GR", dialCode: "+30", format: "+30 XXX XXX XXXX" },
  { name: "Grenada", code: "GD", dialCode: "+1-473", format: "+1 473 XXX XXXX" },
  { name: "Guatemala", code: "GT", dialCode: "+502", format: "+502 XXXX XXXX" },
  { name: "Guinea", code: "GN", dialCode: "+224", format: "+224 XXX XX XX XX" },
  { name: "Guinea-Bissau", code: "GW", dialCode: "+245", format: "+245 XXX XXXX" },
  { name: "Guyana", code: "GY", dialCode: "+592", format: "+592 XXX XXXX" },
  { name: "Haiti", code: "HT", dialCode: "+509", format: "+509 XXXX XXXX" },
  { name: "Honduras", code: "HN", dialCode: "+504", format: "+504 XXXX XXXX" },
  { name: "Hungary", code: "HU", dialCode: "+36", format: "+36 XX XXX XXXX" },
  { name: "Iceland", code: "IS", dialCode: "+354", format: "+354 XXX XXXX" },
  { name: "India", code: "IN", dialCode: "+91", format: "+91 XXXXX XXXXX" },
  { name: "Indonesia", code: "ID", dialCode: "+62", format: "+62 XXX XXXX XXXX" },
  { name: "Iran", code: "IR", dialCode: "+98", format: "+98 XXX XXX XXXX" },
  { name: "Iraq", code: "IQ", dialCode: "+964", format: "+964 XXX XXX XXXX" },
  { name: "Ireland", code: "IE", dialCode: "+353", format: "+353 XX XXX XXXX" },
  { name: "Israel", code: "IL", dialCode: "+972", format: "+972 XX XXX XXXX" },
  { name: "Italy", code: "IT", dialCode: "+39", format: "+39 XXX XXX XXXX" },
  { name: "Ivory Coast", code: "CI", dialCode: "+225", format: "+225 XX XX XX XX XX" },
  { name: "Jamaica", code: "JM", dialCode: "+1-876", format: "+1 876 XXX XXXX" },
  { name: "Japan", code: "JP", dialCode: "+81", format: "+81 XX XXXX XXXX" },
  { name: "Jordan", code: "JO", dialCode: "+962", format: "+962 X XXXX XXXX" },
  { name: "Kazakhstan", code: "KZ", dialCode: "+7", format: "+7 XXX XXX XX XX" },
  { name: "Kenya", code: "KE", dialCode: "+254", format: "+254 XXX XXX XXX" },
  { name: "Kiribati", code: "KI", dialCode: "+686", format: "+686 XXXX XXXX" },
  { name: "Kosovo", code: "XK", dialCode: "+383", format: "+383 XX XXX XXX" },
  { name: "Kuwait", code: "KW", dialCode: "+965", format: "+965 XXXX XXXX" },
  { name: "Kyrgyzstan", code: "KG", dialCode: "+996", format: "+996 XXX XXX XXX" },
  { name: "Laos", code: "LA", dialCode: "+856", format: "+856 XX XX XXX XXX" },
  { name: "Latvia", code: "LV", dialCode: "+371", format: "+371 XXXX XXXX" },
  { name: "Lebanon", code: "LB", dialCode: "+961", format: "+961 XX XXX XXX" },
  { name: "Lesotho", code: "LS", dialCode: "+266", format: "+266 XXXX XXXX" },
  { name: "Liberia", code: "LR", dialCode: "+231", format: "+231 XX XXX XXXX" },
  { name: "Libya", code: "LY", dialCode: "+218", format: "+218 XX XXX XXXX" },
  { name: "Liechtenstein", code: "LI", dialCode: "+423", format: "+423 XXX XX XX" },
  { name: "Lithuania", code: "LT", dialCode: "+370", format: "+370 XXX XXXXX" },
  { name: "Luxembourg", code: "LU", dialCode: "+352", format: "+352 XXX XXX XXX" },
  { name: "Madagascar", code: "MG", dialCode: "+261", format: "+261 XX XX XXX XX" },
  { name: "Malawi", code: "MW", dialCode: "+265", format: "+265 X XXXX XXXX" },
  { name: "Malaysia", code: "MY", dialCode: "+60", format: "+60 XX XXXX XXXX" },
  { name: "Maldives", code: "MV", dialCode: "+960", format: "+960 XXX XXXX" },
  { name: "Mali", code: "ML", dialCode: "+223", format: "+223 XX XX XX XX" },
  { name: "Malta", code: "MT", dialCode: "+356", format: "+356 XXXX XXXX" },
  { name: "Marshall Islands", code: "MH", dialCode: "+692", format: "+692 XXX XXXX" },
  { name: "Mauritania", code: "MR", dialCode: "+222", format: "+222 XXXX XXXX" },
  { name: "Mauritius", code: "MU", dialCode: "+230", format: "+230 XXXX XXXX" },
  { name: "Mexico", code: "MX", dialCode: "+52", format: "+52 XX XXXX XXXX" },
  { name: "Micronesia", code: "FM", dialCode: "+691", format: "+691 XXX XXXX" },
  { name: "Moldova", code: "MD", dialCode: "+373", format: "+373 XX XXX XXX" },
  { name: "Monaco", code: "MC", dialCode: "+377", format: "+377 XX XX XX XX" },
  { name: "Mongolia", code: "MN", dialCode: "+976", format: "+976 XX XX XXXX" },
  { name: "Montenegro", code: "ME", dialCode: "+382", format: "+382 XX XXX XXX" },
  { name: "Morocco", code: "MA", dialCode: "+212", format: "+212 XXX XXX XXX" },
  { name: "Mozambique", code: "MZ", dialCode: "+258", format: "+258 XX XXX XXXX" },
  { name: "Myanmar", code: "MM", dialCode: "+95", format: "+95 XX XXX XXXX" },
  { name: "Namibia", code: "NA", dialCode: "+264", format: "+264 XX XXX XXXX" },
  { name: "Nauru", code: "NR", dialCode: "+674", format: "+674 XXX XXXX" },
  { name: "Nepal", code: "NP", dialCode: "+977", format: "+977 XX XXXX XXXX" },
  { name: "Netherlands", code: "NL", dialCode: "+31", format: "+31 X XXXX XXXX" },
  { name: "New Zealand", code: "NZ", dialCode: "+64", format: "+64 XX XXX XXXX" },
  { name: "Nicaragua", code: "NI", dialCode: "+505", format: "+505 XXXX XXXX" },
  { name: "Niger", code: "NE", dialCode: "+227", format: "+227 XX XX XX XX" },
  { name: "Nigeria", code: "NG", dialCode: "+234", format: "+234 XXX XXX XXXX" },
  { name: "North Korea", code: "KP", dialCode: "+850", format: "+850 XXX XXX XXXX" },
  { name: "North Macedonia", code: "MK", dialCode: "+389", format: "+389 XX XXX XXX" },
  { name: "Norway", code: "NO", dialCode: "+47", format: "+47 XXX XX XXX" },
  { name: "Oman", code: "OM", dialCode: "+968", format: "+968 XXXX XXXX" },
  { name: "Pakistan", code: "PK", dialCode: "+92", format: "+92 XXX XXXXXXX" },
  { name: "Palau", code: "PW", dialCode: "+680", format: "+680 XXX XXXX" },
  { name: "Palestine", code: "PS", dialCode: "+970", format: "+970 XX XXX XXXX" },
  { name: "Panama", code: "PA", dialCode: "+507", format: "+507 XXXX XXXX" },
  { name: "Papua New Guinea", code: "PG", dialCode: "+675", format: "+675 XXX XXXX" },
  { name: "Paraguay", code: "PY", dialCode: "+595", format: "+595 XXX XXX XXX" },
  { name: "Peru", code: "PE", dialCode: "+51", format: "+51 XXX XXX XXX" },
  { name: "Philippines", code: "PH", dialCode: "+63", format: "+63 XXX XXX XXXX" },
  { name: "Poland", code: "PL", dialCode: "+48", format: "+48 XXX XXX XXX" },
  { name: "Portugal", code: "PT", dialCode: "+351", format: "+351 XXX XXX XXX" },
  { name: "Qatar", code: "QA", dialCode: "+974", format: "+974 XXXX XXXX" },
  { name: "Romania", code: "RO", dialCode: "+40", format: "+40 XXX XXX XXX" },
  { name: "Russia", code: "RU", dialCode: "+7", format: "+7 XXX XXX XX XX" },
  { name: "Rwanda", code: "RW", dialCode: "+250", format: "+250 XXX XXX XXX" },
  { name: "Saint Kitts and Nevis", code: "KN", dialCode: "+1-869", format: "+1 869 XXX XXXX" },
  { name: "Saint Lucia", code: "LC", dialCode: "+1-758", format: "+1 758 XXX XXXX" },
  { name: "Saint Vincent and the Grenadines", code: "VC", dialCode: "+1-784", format: "+1 784 XXX XXXX" },
  { name: "Samoa", code: "WS", dialCode: "+685", format: "+685 XX XXXX" },
  { name: "San Marino", code: "SM", dialCode: "+378", format: "+378 XXXX XXXXXX" },
  { name: "Sao Tome and Principe", code: "ST", dialCode: "+239", format: "+239 XXX XXXX" },
  { name: "Saudi Arabia", code: "SA", dialCode: "+966", format: "+966 XX XXX XXXX" },
  { name: "Senegal", code: "SN", dialCode: "+221", format: "+221 XX XXX XX XX" },
  { name: "Serbia", code: "RS", dialCode: "+381", format: "+381 XX XXX XXXX" },
  { name: "Seychelles", code: "SC", dialCode: "+248", format: "+248 X XX XX XX" },
  { name: "Sierra Leone", code: "SL", dialCode: "+232", format: "+232 XX XXX XXX" },
  { name: "Singapore", code: "SG", dialCode: "+65", format: "+65 XXXX XXXX" },
  { name: "Slovakia", code: "SK", dialCode: "+421", format: "+421 XXX XXX XXX" },
  { name: "Slovenia", code: "SI", dialCode: "+386", format: "+386 XX XXX XXX" },
  { name: "Solomon Islands", code: "SB", dialCode: "+677", format: "+677 XXXXX" },
  { name: "Somalia", code: "SO", dialCode: "+252", format: "+252 XX XXX XXX" },
  { name: "South Africa", code: "ZA", dialCode: "+27", format: "+27 XX XXX XXXX" },
  { name: "South Korea", code: "KR", dialCode: "+82", format: "+82 XX XXXX XXXX" },
  { name: "South Sudan", code: "SS", dialCode: "+211", format: "+211 XX XXX XXXX" },
  { name: "Spain", code: "ES", dialCode: "+34", format: "+34 XXX XXX XXX" },
  { name: "Sri Lanka", code: "LK", dialCode: "+94", format: "+94 XX XXX XXXX" },
  { name: "Sudan", code: "SD", dialCode: "+249", format: "+249 XX XXX XXXX" },
  { name: "Suriname", code: "SR", dialCode: "+597", format: "+597 XXX XXXX" },
  { name: "Sweden", code: "SE", dialCode: "+46", format: "+46 XX XXX XX XX" },
  { name: "Switzerland", code: "CH", dialCode: "+41", format: "+41 XX XXX XX XX" },
  { name: "Syria", code: "SY", dialCode: "+963", format: "+963 XX XXXX XXX" },
  { name: "Taiwan", code: "TW", dialCode: "+886", format: "+886 X XXXX XXXX" },
  { name: "Tajikistan", code: "TJ", dialCode: "+992", format: "+992 XX XXX XXXX" },
  { name: "Tanzania", code: "TZ", dialCode: "+255", format: "+255 XXX XXX XXX" },
  { name: "Thailand", code: "TH", dialCode: "+66", format: "+66 XX XXX XXXX" },
  { name: "Timor-Leste", code: "TL", dialCode: "+670", format: "+670 XXXX XXXX" },
  { name: "Togo", code: "TG", dialCode: "+228", format: "+228 XX XXX XXX" },
  { name: "Tonga", code: "TO", dialCode: "+676", format: "+676 XXXXX" },
  { name: "Trinidad and Tobago", code: "TT", dialCode: "+1-868", format: "+1 868 XXX XXXX" },
  { name: "Tunisia", code: "TN", dialCode: "+216", format: "+216 XX XXX XXX" },
  { name: "Turkey", code: "TR", dialCode: "+90", format: "+90 XXX XXX XX XX" },
  { name: "Turkmenistan", code: "TM", dialCode: "+993", format: "+993 XX XXXXXX" },
  { name: "Tuvalu", code: "TV", dialCode: "+688", format: "+688 XXXXX" },
  { name: "Uganda", code: "UG", dialCode: "+256", format: "+256 XXX XXX XXX" },
  { name: "Ukraine", code: "UA", dialCode: "+380", format: "+380 XX XXX XX XX" },
  { name: "United Arab Emirates", code: "AE", dialCode: "+971", format: "+971 XX XXX XXXX" },
  { name: "United Kingdom", code: "GB", dialCode: "+44", format: "+44 XXXX XXXXXX" },
  { name: "United States", code: "US", dialCode: "+1", format: "+1 XXX XXX XXXX" },
  { name: "Uruguay", code: "UY", dialCode: "+598", format: "+598 XX XXX XXX" },
  { name: "Uzbekistan", code: "UZ", dialCode: "+998", format: "+998 XX XXX XX XX" },
  { name: "Vanuatu", code: "VU", dialCode: "+678", format: "+678 XXXXX" },
  { name: "Vatican City", code: "VA", dialCode: "+379", format: "+379 XXXX XXXX" },
  { name: "Venezuela", code: "VE", dialCode: "+58", format: "+58 XXX XXX XXXX" },
  { name: "Vietnam", code: "VN", dialCode: "+84", format: "+84 XX XXXX XXXX" },
  { name: "Yemen", code: "YE", dialCode: "+967", format: "+967 XXX XXX XXX" },
  { name: "Zambia", code: "ZM", dialCode: "+260", format: "+260 XX XXX XXXX" },
  { name: "Zimbabwe", code: "ZW", dialCode: "+263", format: "+263 XX XXX XXXX" },
];

export const countryPhoneCodes = countries.map(c => ({
  label: `${c.name} (${c.dialCode})`,
  value: c.dialCode,
  format: c.format,
  code: c.code,
}));
