// LLC Formation Data
const llcData = {
    "Alabama": {
        stateFee: 208,
        agentFee: 49,
        uniqueAddress: 0,
        vykeNumber: 20,
        serviceCharges: 100,
        annualReportFee: 0,
        annualReportDeadline: "N/A",
        stateTaxRate: "6.50%",
        federalTax: "Pass-through",
        additionalRequirements: "Business Privilege Tax: $100 min",
        warnings: ["Business Privilege Tax of $100 minimum annually"],
        includes: [
            "USA Number",
            "USA State Verified Registered Agent",
            "Unique address with unique Suite Number",
            "Article of organization",
            "Employer Identification Number (EIN)",
            "Beneficial Ownership Information Report (BOI)",
            "Operating Agreement",
            "1 Year Domain",
            "3 Month WordPress Website",
            "3 Month Business Email"
        ]
    },
    "Alaska": {
        stateFee: 260,
        agentFee: 49,
        uniqueAddress: 0,
        vykeNumber: 20,
        serviceCharges: 100,
        annualReportFee: 100,
        annualReportDeadline: "By Jan 2",
        stateTaxRate: "0-9.4%",
        federalTax: "Pass-through",
        additionalRequirements: "Biennial report every 2 years",
        warnings: ["Biennial report required every 2 years"],
        includes: [
            "USA Number",
            "USA State Verified Registered Agent",
            "Unique address with unique Suite Number",
            "Article of organization",
            "Employer Identification Number (EIN)",
            "Beneficial Ownership Information Report (BOI)",
            "Operating Agreement",
            "1 Year Domain",
            "3 Month WordPress Website",
            "3 Month Business Email"
        ]
    },
    "Arizona": {
        stateFee: 52,
        agentFee: 49,
        uniqueAddress: 0,
        vykeNumber: 20,
        serviceCharges: 100,
        annualReportFee: 0,
        annualReportDeadline: "Anniversary month",
        stateTaxRate: "2.50%",
        federalTax: "Pass-through",
        additionalRequirements: "No annual report required",
        warnings: ["Must publish in newspaper for 3 consecutive weeks ($50-$300)"],
        includes: [
            "USA Number",
            "USA State Verified Registered Agent",
            "Unique address with unique Suite Number",
            "Article of organization",
            "Employer Identification Number (EIN)",
            "Beneficial Ownership Information Report (BOI)",
            "Operating Agreement",
            "1 Year Domain",
            "3 Month WordPress Website",
            "3 Month Business Email"
        ]
    },
    "Arkansas": {
        stateFee: 46.8,
        agentFee: 49,
        uniqueAddress: 0,
        vykeNumber: 20,
        serviceCharges: 100,
        annualReportFee: 150,
        annualReportDeadline: "1-May",
        stateTaxRate: "1-5.9%",
        federalTax: "Pass-through",
        additionalRequirements: "Franchise Tax: $150 min",
        warnings: ["Franchise Tax of $150 minimum annually"],
        includes: [
            "USA Number",
            "USA State Verified Registered Agent",
            "Unique address with unique Suite Number",
            "Article of organization",
            "Employer Identification Number (EIN)",
            "Beneficial Ownership Information Report (BOI)",
            "Operating Agreement",
            "1 Year Domain",
            "3 Month WordPress Website",
            "3 Month Business Email"
        ]
    },
    "California": {
        stateFee: 93.6,
        agentFee: 49,
        uniqueAddress: 49,
        vykeNumber: 20,
        serviceCharges: 100,
        annualReportFee: 20,
        annualReportDeadline: "Anniversary month",
        stateTaxRate: "8.84%",
        federalTax: "Pass-through",
        additionalRequirements: "$800 min franchise tax annually",
        warnings: [
            "⚠️ HIGH ALERT: $800 minimum franchise tax EVERY YEAR regardless of income",
            "Additional: Statement of Information (Form LLC-12) - $20 biennial fee",
            "Foreign Owners: Must withhold 7% on distributions to non-residents",
            "Penalty: $250/month for late franchise tax payment"
        ],
        highAlert: true,
        includes: [
            "USA Number",
            "USA State Verified Registered Agent",
            "Unique address with unique Suite Number",
            "Article of organization",
            "Employer Identification Number (EIN)",
            "Beneficial Ownership Information Report (BOI)",
            "Operating Agreement",
            "1 Year Domain",
            "3 Month WordPress Website",
            "3 Month Business Email"
        ]
    },
    "Colorado": {
        stateFee: 52,
        agentFee: 35,
        uniqueAddress: 0,
        vykeNumber: 20,
        serviceCharges: 100,
        annualReportFee: 10,
        annualReportDeadline: "Anniversary month",
        stateTaxRate: "4.55%",
        federalTax: "Pass-through",
        additionalRequirements: "Periodic report every 2 years",
        warnings: ["Periodic report required every 2 years"],
        includes: [
            "USA Number",
            "USA State Verified Registered Agent",
            "Unique address with unique Suite Number",
            "Article of organization",
            "Employer Identification Number (EIN)",
            "Beneficial Ownership Information Report (BOI)",
            "Operating Agreement",
            "1 Year Domain",
            "3 Month WordPress Website",
            "3 Month Business Email"
        ]
    },
    "Connecticut": {
        stateFee: 124.8,
        agentFee: 49,
        uniqueAddress: 0,
        vykeNumber: 20,
        serviceCharges: 100,
        annualReportFee: 80,
        annualReportDeadline: "Anniversary month",
        stateTaxRate: "6.99%",
        federalTax: "Pass-through",
        additionalRequirements: "Business Entity Tax: $250",
        warnings: ["Business Entity Tax of $250 annually"],
        includes: [
            "USA Number",
            "USA State Verified Registered Agent",
            "Unique address with unique Suite Number",
            "Article of organization",
            "Employer Identification Number (EIN)",
            "Beneficial Ownership Information Report (BOI)",
            "Operating Agreement",
            "1 Year Domain",
            "3 Month WordPress Website",
            "3 Month Business Email"
        ]
    },
    "Delaware": {
        stateFee: 115,
        agentFee: 29,
        uniqueAddress: 49,
        vykeNumber: 20,
        serviceCharges: 50,
        annualReportFee: 300,
        annualReportDeadline: "1-Jun",
        stateTaxRate: "8.70%",
        federalTax: "Pass-through",
        additionalRequirements: "Franchise Tax: $300",
        warnings: [
            "⚠️ HIGH ALERT: Franchise Tax of $300 annually",
            "Must maintain Delaware registered agent",
            "Popular for business-friendly courts but expensive"
        ],
        highAlert: true,
        includes: [
            "USA Number",
            "USA State Verified Registered Agent",
            "Unique address with unique Suite Number",
            "Article of organization",
            "Employer Identification Number (EIN)",
            "Beneficial Ownership Information Report (BOI)",
            "Operating Agreement",
            "1 Year Domain",
            "3 Month WordPress Website",
            "3 Month Business Email"
        ]
    },
    "Florida": {
        stateFee: 130,
        agentFee: 35,
        uniqueAddress: 49,
        vykeNumber: 20,
        serviceCharges: 50,
        annualReportFee: 138.75,
        annualReportDeadline: "1-May",
        stateTaxRate: "5.50%",
        federalTax: "Pass-through",
        additionalRequirements: "Annual report required",
        warnings: ["Annual report fee of $138.75"],
        recommended: true,
        taxFree: false,
        includes: [
            "USA Number",
            "USA State Verified Registered Agent",
            "Unique address with unique Suite Number",
            "Article of organization",
            "Employer Identification Number (EIN)",
            "Beneficial Ownership Information Report (BOI)",
            "Operating Agreement",
            "1 Year Domain",
            "3 Month WordPress Website",
            "3 Month Business Email"
        ]
    },
    "Georgia": {
        stateFee: 104,
        agentFee: 25,
        uniqueAddress: 49,
        vykeNumber: 20,
        serviceCharges: 100,
        annualReportFee: 50,
        annualReportDeadline: "Between Jan 1 - Apr 1",
        stateTaxRate: "5.75%",
        federalTax: "Pass-through",
        additionalRequirements: "Annual registration",
        warnings: ["Must publish in county newspaper once a week for 2 weeks ($40-$100)"],
        includes: [
            "USA Number",
            "USA State Verified Registered Agent",
            "Unique address with unique Suite Number",
            "Article of organization",
            "Employer Identification Number (EIN)",
            "Beneficial Ownership Information Report (BOI)",
            "Operating Agreement",
            "1 Year Domain",
            "3 Month WordPress Website",
            "3 Month Business Email"
        ]
    },
    "Hawaii": {
        stateFee: 52,
        agentFee: 49,
        uniqueAddress: 0,
        vykeNumber: 20,
        serviceCharges: 100,
        annualReportFee: 15,
        annualReportDeadline: "Anniversary quarter",
        stateTaxRate: "6.4-11%",
        federalTax: "Pass-through",
        additionalRequirements: "General Excise Tax License",
        warnings: ["General Excise Tax License required"],
        includes: [
            "USA Number",
            "USA State Verified Registered Agent",
            "Unique address with unique Suite Number",
            "Article of organization",
            "Employer Identification Number (EIN)",
            "Beneficial Ownership Information Report (BOI)",
            "Operating Agreement",
            "1 Year Domain",
            "3 Month WordPress Website",
            "3 Month Business Email"
        ]
    },
    "Idaho": {
        stateFee: 104,
        agentFee: 35,
        uniqueAddress: 49,
        vykeNumber: 20,
        serviceCharges: 100,
        annualReportFee: 0,
        annualReportDeadline: "N/A",
        stateTaxRate: "6%",
        federalTax: "Pass-through",
        additionalRequirements: "No annual report required",
        warnings: ["No annual report required - business friendly"],
        includes: [
            "USA Number",
            "USA State Verified Registered Agent",
            "Unique address with unique Suite Number",
            "Article of organization",
            "Employer Identification Number (EIN)",
            "Beneficial Ownership Information Report (BOI)",
            "Operating Agreement",
            "1 Year Domain",
            "3 Month WordPress Website",
            "3 Month Business Email"
        ]
    },
    "Illinois": {
        stateFee: 156,
        agentFee: 49,
        uniqueAddress: 49,
        vykeNumber: 20,
        serviceCharges: 100,
        annualReportFee: 75,
        annualReportDeadline: "Anniversary month",
        stateTaxRate: "9.50%",
        federalTax: "Pass-through",
        additionalRequirements: "Annual report required",
        warnings: [
            "⚠️ HIGH ALERT: 1.5% Personal Property Replacement Tax on all LLCs",
            "Annual report must be filed online only",
            "Foreign Owners: Must withhold 7.3% on distributions"
        ],
        highAlert: true,
        includes: [
            "USA Number",
            "USA State Verified Registered Agent",
            "Unique address with unique Suite Number",
            "Article of organization",
            "Employer Identification Number (EIN)",
            "Beneficial Ownership Information Report (BOI)",
            "Operating Agreement",
            "1 Year Domain",
            "3 Month WordPress Website",
            "3 Month Business Email"
        ]
    },
    "Indiana": {
        stateFee: 93.6,
        agentFee: 49,
        uniqueAddress: 0,
        vykeNumber: 20,
        serviceCharges: 100,
        annualReportFee: 31,
        annualReportDeadline: "Anniversary month",
        stateTaxRate: "3.23%",
        federalTax: "Pass-through",
        additionalRequirements: "Biennial report every 2 years",
        warnings: ["Biennial report required every 2 years"],
        includes: [
            "USA Number",
            "USA State Verified Registered Agent",
            "Unique address with unique Suite Number",
            "Article of organization",
            "Employer Identification Number (EIN)",
            "Beneficial Ownership Information Report (BOI)",
            "Operating Agreement",
            "1 Year Domain",
            "3 Month WordPress Website",
            "3 Month Business Email"
        ]
    },
    "Iowa": {
        stateFee: 52,
        agentFee: 49,
        uniqueAddress: 0,
        vykeNumber: 20,
        serviceCharges: 100,
        annualReportFee: 60,
        annualReportDeadline: "Apr 1 (biennial)",
        stateTaxRate: "5.4-8.53%",
        federalTax: "Pass-through",
        additionalRequirements: "Biennial report every 2 years",
        warnings: ["Biennial report required every 2 years"],
        includes: [
            "USA Number",
            "USA State Verified Registered Agent",
            "Unique address with unique Suite Number",
            "Article of organization",
            "Employer Identification Number (EIN)",
            "Beneficial Ownership Information Report (BOI)",
            "Operating Agreement",
            "1 Year Domain",
            "3 Month WordPress Website",
            "3 Month Business Email"
        ]
    },
    "Kansas": {
        stateFee: 166.4,
        agentFee: 49,
        uniqueAddress: 0,
        vykeNumber: 20,
        serviceCharges: 100,
        annualReportFee: 55,
        annualReportDeadline: "15th day of 4th month",
        stateTaxRate: "4-7%",
        federalTax: "Pass-through",
        additionalRequirements: "Annual report required",
        warnings: ["Annual report required"],
        includes: [
            "USA Number",
            "USA State Verified Registered Agent",
            "Unique address with unique Suite Number",
            "Article of organization",
            "Employer Identification Number (EIN)",
            "Beneficial Ownership Information Report (BOI)",
            "Operating Agreement",
            "1 Year Domain",
            "3 Month WordPress Website",
            "3 Month Business Email"
        ]
    },
    "Kentucky": {
        stateFee: 41.6,
        agentFee: 49,
        uniqueAddress: 0,
        vykeNumber: 20,
        serviceCharges: 100,
        annualReportFee: 15,
        annualReportDeadline: "30-Jun",
        stateTaxRate: "5%",
        federalTax: "Pass-through",
        additionalRequirements: "Annual report required",
        warnings: ["Annual report required"],
        includes: [
            "USA Number",
            "USA State Verified Registered Agent",
            "Unique address with unique Suite Number",
            "Article of organization",
            "Employer Identification Number (EIN)",
            "Beneficial Ownership Information Report (BOI)",
            "Operating Agreement",
            "1 Year Domain",
            "3 Month WordPress Website",
            "3 Month Business Email"
        ]
    },
    "Louisiana": {
        stateFee: 104,
        agentFee: 49,
        uniqueAddress: 0,
        vykeNumber: 20,
        serviceCharges: 100,
        annualReportFee: 35,
        annualReportDeadline: "Anniversary month",
        stateTaxRate: "3.5-7.5%",
        federalTax: "Pass-through",
        additionalRequirements: "Annual report required",
        warnings: ["Annual report required"],
        includes: [
            "USA Number",
            "USA State Verified Registered Agent",
            "Unique address with unique Suite Number",
            "Article of organization",
            "Employer Identification Number (EIN)",
            "Beneficial Ownership Information Report (BOI)",
            "Operating Agreement",
            "1 Year Domain",
            "3 Month WordPress Website",
            "3 Month Business Email"
        ]
    },
    "Maine": {
        stateFee: 182,
        agentFee: 49,
        uniqueAddress: 0,
        vykeNumber: 20,
        serviceCharges: 100,
        annualReportFee: 85,
        annualReportDeadline: "1-Jun",
        stateTaxRate: "7.15%",
        federalTax: "Pass-through",
        additionalRequirements: "Annual report required",
        warnings: ["Annual report required"],
        includes: [
            "USA Number",
            "USA State Verified Registered Agent",
            "Unique address with unique Suite Number",
            "Article of organization",
            "Employer Identification Number (EIN)",
            "Beneficial Ownership Information Report (BOI)",
            "Operating Agreement",
            "1 Year Domain",
            "3 Month WordPress Website",
            "3 Month Business Email"
        ]
    },
    "Maryland": {
        stateFee: 104,
        agentFee: 49,
        uniqueAddress: 0,
        vykeNumber: 20,
        serviceCharges: 100,
        annualReportFee: 300,
        annualReportDeadline: "15-Apr",
        stateTaxRate: "8.25%",
        federalTax: "Pass-through",
        additionalRequirements: "Personal Property Return",
        warnings: ["Personal Property Return required annually"],
        includes: [
            "USA Number",
            "USA State Verified Registered Agent",
            "Unique address with unique Suite Number",
            "Article of organization",
            "Employer Identification Number (EIN)",
            "Beneficial Ownership Information Report (BOI)",
            "Operating Agreement",
            "1 Year Domain",
            "3 Month WordPress Website",
            "3 Month Business Email"
        ]
    },
    "Massachusetts": {
        stateFee: 520,
        agentFee: 49,
        uniqueAddress: 0,
        vykeNumber: 20,
        serviceCharges: 100,
        annualReportFee: 500,
        annualReportDeadline: "Anniversary month",
        stateTaxRate: "8.80%",
        federalTax: "Pass-through",
        additionalRequirements: "Annual report required",
        warnings: [
            "⚠️ HIGH ALERT: $500 annual fee regardless of income",
            "Annual report due on anniversary date",
            "Foreign Owners: 5.1% withholding on non-resident members"
        ],
        highAlert: true,
        includes: [
            "USA Number",
            "USA State Verified Registered Agent",
            "Unique address with unique Suite Number",
            "Article of organization",
            "Employer Identification Number (EIN)",
            "Beneficial Ownership Information Report (BOI)",
            "Operating Agreement",
            "1 Year Domain",
            "3 Month WordPress Website",
            "3 Month Business Email"
        ]
    },
    "Michigan": {
        stateFee: 52,
        agentFee: 49,
        uniqueAddress: 0,
        vykeNumber: 20,
        serviceCharges: 100,
        annualReportFee: 25,
        annualReportDeadline: "15-Feb",
        stateTaxRate: "6%",
        federalTax: "Pass-through",
        additionalRequirements: "Annual statement",
        warnings: ["Annual statement required"],
        includes: [
            "USA Number",
            "USA State Verified Registered Agent",
            "Unique address with unique Suite Number",
            "Article of organization",
            "Employer Identification Number (EIN)",
            "Beneficial Ownership Information Report (BOI)",
            "Operating Agreement",
            "1 Year Domain",
            "3 Month WordPress Website",
            "3 Month Business Email"
        ]
    },
    "Minnesota": {
        stateFee: 140.4,
        agentFee: 49,
        uniqueAddress: 0,
        vykeNumber: 20,
        serviceCharges: 100,
        annualReportFee: 0,
        annualReportDeadline: "31-Dec",
        stateTaxRate: "9.85%",
        federalTax: "Pass-through",
        additionalRequirements: "Annual renewal",
        warnings: ["Annual renewal required"],
        includes: [
            "USA Number",
            "USA State Verified Registered Agent",
            "Unique address with unique Suite Number",
            "Article of organization",
            "Employer Identification Number (EIN)",
            "Beneficial Ownership Information Report (BOI)",
            "Operating Agreement",
            "1 Year Domain",
            "3 Month WordPress Website",
            "3 Month Business Email"
        ]
    },
    "Mississippi": {
        stateFee: 52,
        agentFee: 49,
        uniqueAddress: 0,
        vykeNumber: 20,
        serviceCharges: 100,
        annualReportFee: 0,
        annualReportDeadline: "N/A",
        stateTaxRate: "4-5%",
        federalTax: "Pass-through",
        additionalRequirements: "No annual report required",
        warnings: ["No annual report required - business friendly"],
        includes: [
            "USA Number",
            "USA State Verified Registered Agent",
            "Unique address with unique Suite Number",
            "Article of organization",
            "Employer Identification Number (EIN)",
            "Beneficial Ownership Information Report (BOI)",
            "Operating Agreement",
            "1 Year Domain",
            "3 Month WordPress Website",
            "3 Month Business Email"
        ]
    },
    "Missouri": {
        stateFee: 52,
        agentFee: 40,
        uniqueAddress: 0,
        vykeNumber: 20,
        serviceCharges: 100,
        annualReportFee: 0,
        annualReportDeadline: "N/A",
        stateTaxRate: "4.95%",
        federalTax: "Pass-through",
        additionalRequirements: "No annual report required",
        warnings: ["No annual report required - business friendly"],
        includes: [
            "USA Number",
            "USA State Verified Registered Agent",
            "Unique address with unique Suite Number",
            "Article of organization",
            "Employer Identification Number (EIN)",
            "Beneficial Ownership Information Report (BOI)",
            "Operating Agreement",
            "1 Year Domain",
            "3 Month WordPress Website",
            "3 Month Business Email"
        ]
    },
    "Montana": {
        stateFee: 36.4,
        agentFee: 45,
        uniqueAddress: 49,
        vykeNumber: 20,
        serviceCharges: 50,
        annualReportFee: 20,
        annualReportDeadline: "15-Apr",
        stateTaxRate: "6.75%",
        federalTax: "Pass-through",
        additionalRequirements: "Annual report required",
        warnings: ["Annual report required"],
        recommended: true,
        taxFree: false,
        includes: [
            "USA Number",
            "USA State Verified Registered Agent",
            "Unique address with unique Suite Number",
            "Article of organization",
            "Employer Identification Number (EIN)",
            "Beneficial Ownership Information Report (BOI)",
            "Operating Agreement",
            "1 Year Domain",
            "3 Month WordPress Website",
            "3 Month Business Email"
        ]
    },
    "Nebraska": {
        stateFee: 104,
        agentFee: 49,
        uniqueAddress: 0,
        vykeNumber: 20,
        serviceCharges: 100,
        annualReportFee: 13,
        annualReportDeadline: "Apr 1 (biennial)",
        stateTaxRate: "6.84%",
        federalTax: "Pass-through",
        additionalRequirements: "Biennial report every 2 years",
        warnings: ["Must publish in newspaper for 3 consecutive weeks ($100-$200)"],
        includes: [
            "USA Number",
            "USA State Verified Registered Agent",
            "Unique address with unique Suite Number",
            "Article of organization",
            "Employer Identification Number (EIN)",
            "Beneficial Ownership Information Report (BOI)",
            "Operating Agreement",
            "1 Year Domain",
            "3 Month WordPress Website",
            "3 Month Business Email"
        ]
    },
    "Nevada": {
        stateFee: 442,
        agentFee: 35,
        uniqueAddress: 49,
        vykeNumber: 20,
        serviceCharges: 100,
        annualReportFee: 150,
        annualReportDeadline: "End of anniversary month",
        stateTaxRate: "0%",
        federalTax: "Pass-through",
        additionalRequirements: "Annual List, Business License: $200",
        warnings: ["Business License fee of $200 annually"],
        taxFree: true,
        includes: [
            "USA Number",
            "USA State Verified Registered Agent",
            "Unique address with unique Suite Number",
            "Article of organization",
            "Employer Identification Number (EIN)",
            "Beneficial Ownership Information Report (BOI)",
            "Operating Agreement",
            "1 Year Domain",
            "3 Month WordPress Website",
            "3 Month Business Email"
        ]
    },
    "New Hampshire": {
        stateFee: 104,
        agentFee: 49,
        uniqueAddress: 0,
        vykeNumber: 20,
        serviceCharges: 100,
        annualReportFee: 100,
        annualReportDeadline: "1-Apr",
        stateTaxRate: "7.60%",
        federalTax: "Pass-through",
        additionalRequirements: "Annual report required",
        warnings: ["Annual report required"],
        includes: [
            "USA Number",
            "USA State Verified Registered Agent",
            "Unique address with unique Suite Number",
            "Article of organization",
            "Employer Identification Number (EIN)",
            "Beneficial Ownership Information Report (BOI)",
            "Operating Agreement",
            "1 Year Domain",
            "3 Month WordPress Website",
            "3 Month Business Email"
        ]
    },
    "New Jersey": {
        stateFee: 130,
        agentFee: 49,
        uniqueAddress: 0,
        vykeNumber: 20,
        serviceCharges: 100,
        annualReportFee: 75,
        annualReportDeadline: "Anniversary month",
        stateTaxRate: "6.625-11.5%",
        federalTax: "Pass-through",
        additionalRequirements: "Annual report required",
        warnings: ["Annual report required"],
        includes: [
            "USA Number",
            "USA State Verified Registered Agent",
            "Unique address with unique Suite Number",
            "Article of organization",
            "Employer Identification Number (EIN)",
            "Beneficial Ownership Information Report (BOI)",
            "Operating Agreement",
            "1 Year Domain",
            "3 Month WordPress Website",
            "3 Month Business Email"
        ]
    },
    "New Mexico": {
        stateFee: 52,
        agentFee: 35,
        uniqueAddress: 49,
        vykeNumber: 20,
        serviceCharges: 100,
        annualReportFee: 0,
        annualReportDeadline: "N/A",
        stateTaxRate: "4.9-11.3%",
        federalTax: "Pass-through",
        additionalRequirements: "No annual report required",
        warnings: ["No annual report required - business friendly"],
        includes: [
            "USA Number",
            "USA State Verified Registered Agent",
            "Unique address with unique Suite Number",
            "Article of organization",
            "Employer Identification Number (EIN)",
            "Beneficial Ownership Information Report (BOI)",
            "Operating Agreement",
            "1 Year Domain",
            "3 Month WordPress Website",
            "3 Month Business Email"
        ]
    },
    "New York": {
        stateFee: 598,
        agentFee: 49,
        uniqueAddress: 49,
        vykeNumber: 20,
        serviceCharges: 100,
        annualReportFee: 9,
        annualReportDeadline: "Anniversary month",
        stateTaxRate: "6.50%",
        federalTax: "Pass-through",
        additionalRequirements: "Biennial statement every 2 years",
        warnings: [
            "⚠️ HIGH ALERT: Publication requirement in 2 newspapers - can cost $500",
            "NYC Unincorporated Business Tax if operating in NYC (4%)",
            "Foreign Owners: Must file IT-2658 for withholding on non-residents"
        ],
        highAlert: true,
        includes: [
            "USA Number",
            "USA State Verified Registered Agent",
            "Unique address with unique Suite Number",
            "Article of organization",
            "Employer Identification Number (EIN)",
            "Beneficial Ownership Information Report (BOI)",
            "Operating Agreement",
            "1 Year Domain",
            "3 Month WordPress Website",
            "3 Month Business Email"
        ]
    },
    "North Carolina": {
        stateFee: 130,
        agentFee: 49,
        uniqueAddress: 0,
        vykeNumber: 20,
        serviceCharges: 100,
        annualReportFee: 200,
        annualReportDeadline: "15-Apr",
        stateTaxRate: "2.50%",
        federalTax: "Pass-through",
        additionalRequirements: "Annual report required",
        warnings: ["Annual report required"],
        includes: [
            "USA Number",
            "USA State Verified Registered Agent",
            "Unique address with unique Suite Number",
            "Article of organization",
            "Employer Identification Number (EIN)",
            "Beneficial Ownership Information Report (BOI)",
            "Operating Agreement",
            "1 Year Domain",
            "3 Month WordPress Website",
            "3 Month Business Email"
        ]
    },
    "North Dakota": {
        stateFee: 140.4,
        agentFee: 30,
        uniqueAddress: 0,
        vykeNumber: 20,
        serviceCharges: 100,
        annualReportFee: 50,
        annualReportDeadline: "15-Nov",
        stateTaxRate: "1.41-2.9%",
        federalTax: "Pass-through",
        additionalRequirements: "Annual report required",
        warnings: ["Annual report required"],
        includes: [
            "USA Number",
            "USA State Verified Registered Agent",
            "Unique address with unique Suite Number",
            "Article of organization",
            "Employer Identification Number (EIN)",
            "Beneficial Ownership Information Report (BOI)",
            "Operating Agreement",
            "1 Year Domain",
            "3 Month WordPress Website",
            "3 Month Business Email"
        ]
    },
    "Ohio": {
        stateFee: 102.96,
        agentFee: 49,
        uniqueAddress: 0,
        vykeNumber: 20,
        serviceCharges: 100,
        annualReportFee: 0,
        annualReportDeadline: "N/A",
        stateTaxRate: "0%",
        federalTax: "Pass-through",
        additionalRequirements: "No annual report, CAT tax applies",
        warnings: ["CAT tax applies to gross receipts"],
        taxFree: true,
        includes: [
            "USA Number",
            "USA State Verified Registered Agent",
            "Unique address with unique Suite Number",
            "Article of organization",
            "Employer Identification Number (EIN)",
            "Beneficial Ownership Information Report (BOI)",
            "Operating Agreement",
            "1 Year Domain",
            "3 Month WordPress Website",
            "3 Month Business Email"
        ]
    },
    "Oklahoma": {
        stateFee: 104,
        agentFee: 49,
        uniqueAddress: 0,
        vykeNumber: 20,
        serviceCharges: 100,
        annualReportFee: 25,
        annualReportDeadline: "Anniversary month",
        stateTaxRate: "4-6%",
        federalTax: "Pass-through",
        additionalRequirements: "Annual certificate",
        warnings: ["Annual certificate required"],
        includes: [
            "USA Number",
            "USA State Verified Registered Agent",
            "Unique address with unique Suite Number",
            "Article of organization",
            "Employer Identification Number (EIN)",
            "Beneficial Ownership Information Report (BOI)",
            "Operating Agreement",
            "1 Year Domain",
            "3 Month WordPress Website",
            "3 Month Business Email"
        ]
    },
    "Oregon": {
        stateFee: 104,
        agentFee: 35,
        uniqueAddress: 49,
        vykeNumber: 20,
        serviceCharges: 100,
        annualReportFee: 100,
        annualReportDeadline: "Anniversary month",
        stateTaxRate: "6.6-9.9%",
        federalTax: "Pass-through",
        additionalRequirements: "Annual report required",
        warnings: ["Annual report required"],
        includes: [
            "USA Number",
            "USA State Verified Registered Agent",
            "Unique address with unique Suite Number",
            "Article of organization",
            "Employer Identification Number (EIN)",
            "Beneficial Ownership Information Report (BOI)",
            "Operating Agreement",
            "1 Year Domain",
            "3 Month WordPress Website",
            "3 Month Business Email"
        ]
    },
    "Pennsylvania": {
        stateFee: 130,
        agentFee: 49,
        uniqueAddress: 0,
        vykeNumber: 20,
        serviceCharges: 100,
        annualReportFee: 7,
        annualReportDeadline: "N/A",
        stateTaxRate: "9.99%",
        federalTax: "Pass-through",
        additionalRequirements: "Decennial filing every 10 years",
        warnings: ["Must advertise in 2 newspapers (1 general, 1 legal) - Cost: $200-$500"],
        includes: [
            "USA Number",
            "USA State Verified Registered Agent",
            "Unique address with unique Suite Number",
            "Article of organization",
            "Employer Identification Number (EIN)",
            "Beneficial Ownership Information Report (BOI)",
            "Operating Agreement",
            "1 Year Domain",
            "3 Month WordPress Website",
            "3 Month Business Email"
        ]
    },
    "Rhode Island": {
        stateFee: 156,
        agentFee: 49,
        uniqueAddress: 0,
        vykeNumber: 20,
        serviceCharges: 100,
        annualReportFee: 50,
        annualReportDeadline: "1-Nov",
        stateTaxRate: "7%",
        federalTax: "Pass-through",
        additionalRequirements: "Annual report required",
        warnings: ["Annual report required"],
        includes: [
            "USA Number",
            "USA State Verified Registered Agent",
            "Unique address with unique Suite Number",
            "Article of organization",
            "Employer Identification Number (EIN)",
            "Beneficial Ownership Information Report (BOI)",
            "Operating Agreement",
            "1 Year Domain",
            "3 Month WordPress Website",
            "3 Month Business Email"
        ]
    },
    "South Carolina": {
        stateFee: 114.4,
        agentFee: 49,
        uniqueAddress: 0,
        vykeNumber: 20,
        serviceCharges: 100,
        annualReportFee: 0,
        annualReportDeadline: "N/A",
        stateTaxRate: "5%",
        federalTax: "Pass-through",
        additionalRequirements: "No annual report, but tax filing",
        warnings: ["Tax filing required but no annual report"],
        includes: [
            "USA Number",
            "USA State Verified Registered Agent",
            "Unique address with unique Suite Number",
            "Article of organization",
            "Employer Identification Number (EIN)",
            "Beneficial Ownership Information Report (BOI)",
            "Operating Agreement",
            "1 Year Domain",
            "3 Month WordPress Website",
            "3 Month Business Email"
        ]
    },
    "South Dakota": {
        stateFee: 156,
        agentFee: 49,
        uniqueAddress: 0,
        vykeNumber: 20,
        serviceCharges: 100,
        annualReportFee: 50,
        annualReportDeadline: "Anniversary month",
        stateTaxRate: "0%",
        federalTax: "Pass-through",
        additionalRequirements: "Annual report required",
        warnings: ["Annual report required"],
        taxFree: true,
        includes: [
            "USA Number",
            "USA State Verified Registered Agent",
            "Unique address with unique Suite Number",
            "Article of organization",
            "Employer Identification Number (EIN)",
            "Beneficial Ownership Information Report (BOI)",
            "Operating Agreement",
            "1 Year Domain",
            "3 Month WordPress Website",
            "3 Month Business Email"
        ]
    },
    "Tennessee": {
        stateFee: 312,
        agentFee: 49,
        uniqueAddress: 0,
        vykeNumber: 20,
        serviceCharges: 100,
        annualReportFee: 300,
        annualReportDeadline: "Within 4 months of fiscal year end",
        stateTaxRate: "6.50%",
        federalTax: "Pass-through",
        additionalRequirements: "Franchise & Excise Tax: $100 min",
        warnings: [
            "⚠️ HIGH ALERT: Franchise Tax: $0.25 per $100 of net worth",
            "Excise Tax: 6.5% on net earnings",
            "Combined filing required"
        ],
        highAlert: true,
        includes: [
            "USA Number",
            "USA State Verified Registered Agent",
            "Unique address with unique Suite Number",
            "Article of organization",
            "Employer Identification Number (EIN)",
            "Beneficial Ownership Information Report (BOI)",
            "Operating Agreement",
            "1 Year Domain",
            "3 Month WordPress Website",
            "3 Month Business Email"
        ]
    },
    "Texas": {
        stateFee: 312,
        agentFee: 35,
        uniqueAddress: 49,
        vykeNumber: 20,
        serviceCharges: 50,
        annualReportFee: 0,
        annualReportDeadline: "May 15 (franchise tax)",
        stateTaxRate: "0%",
        federalTax: "Pass-through",
        additionalRequirements: "Franchise Tax Report (no tax if revenue is less than $1.23M)",
        warnings: ["Franchise Tax Report and Public Information Report is required but no tax if revenue under $1.23M"],
        recommended: true,
        taxFree: true,
        includes: [
            "USA Number",
            "USA State Verified Registered Agent",
            "Unique address with unique Suite Number",
            "Article of organization",
            "Employer Identification Number (EIN)",
            "Beneficial Ownership Information Report (BOI)",
            "Operating Agreement",
            "1 Year Domain",
            "3 Month WordPress Website",
            "3 Month Business Email"
        ]
    },
    "Utah": {
        stateFee: 72.8,
        agentFee: 49,
        uniqueAddress: 49,
        vykeNumber: 20,
        serviceCharges: 100,
        annualReportFee: 20,
        annualReportDeadline: "Anniversary month",
        stateTaxRate: "4.95%",
        federalTax: "Pass-through",
        additionalRequirements: "Annual renewal",
        warnings: ["Annual renewal required"],
        includes: [
            "USA Number",
            "USA State Verified Registered Agent",
            "Unique address with unique Suite Number",
            "Article of organization",
            "Employer Identification Number (EIN)",
            "Beneficial Ownership Information Report (BOI)",
            "Operating Agreement",
            "1 Year Domain",
            "3 Month WordPress Website",
            "3 Month Business Email"
        ]
    },
    "Vermont": {
        stateFee: 130,
        agentFee: 49,
        uniqueAddress: 0,
        vykeNumber: 20,
        serviceCharges: 100,
        annualReportFee: 35,
        annualReportDeadline: "Within 2.5 months of anniversary",
        stateTaxRate: "6-8.75%",
        federalTax: "Pass-through",
        additionalRequirements: "Annual report required",
        warnings: ["Annual report required"],
        includes: [
            "USA Number",
            "USA State Verified Registered Agent",
            "Unique address with unique Suite Number",
            "Article of organization",
            "Employer Identification Number (EIN)",
            "Beneficial Ownership Information Report (BOI)",
            "Operating Agreement",
            "1 Year Domain",
            "3 Month WordPress Website",
            "3 Month Business Email"
        ]
    },
    "Virginia": {
        stateFee: 104,
        agentFee: 49,
        uniqueAddress: 49,
        vykeNumber: 20,
        serviceCharges: 100,
        annualReportFee: 50,
        annualReportDeadline: "Last day of anniversary month",
        stateTaxRate: "6%",
        federalTax: "Pass-through",
        additionalRequirements: "Annual registration fee",
        warnings: ["Annual registration fee required"],
        includes: [
            "USA Number",
            "USA State Verified Registered Agent",
            "Unique address with unique Suite Number",
            "Article of organization",
            "Employer Identification Number (EIN)",
            "Beneficial Ownership Information Report (BOI)",
            "Operating Agreement",
            "1 Year Domain",
            "3 Month WordPress Website",
            "3 Month Business Email"
        ]
    },
    "Washington": {
        stateFee: 208,
        agentFee: 59,
        uniqueAddress: 49,
        vykeNumber: 20,
        serviceCharges: 100,
        annualReportFee: 60,
        annualReportDeadline: "End of anniversary month",
        stateTaxRate: "0%",
        federalTax: "Pass-through",
        additionalRequirements: "B&O Tax on gross receipts",
        warnings: ["B&O Tax applies to gross receipts"],
        taxFree: true,
        includes: [
            "USA Number",
            "USA State Verified Registered Agent",
            "Unique address with unique Suite Number",
            "Article of organization",
            "Employer Identification Number (EIN)",
            "Beneficial Ownership Information Report (BOI)",
            "Operating Agreement",
            "1 Year Domain",
            "3 Month WordPress Website",
            "3 Month Business Email"
        ]
    },
    "West Virginia": {
        stateFee: 104,
        agentFee: 49,
        uniqueAddress: 0,
        vykeNumber: 20,
        serviceCharges: 100,
        annualReportFee: 25,
        annualReportDeadline: "30-Jun",
        stateTaxRate: "6.50%",
        federalTax: "Pass-through",
        additionalRequirements: "Annual report required",
        warnings: ["Annual report required"],
        includes: [
            "USA Number",
            "USA State Verified Registered Agent",
            "Unique address with unique Suite Number",
            "Article of organization",
            "Employer Identification Number (EIN)",
            "Beneficial Ownership Information Report (BOI)",
            "Operating Agreement",
            "1 Year Domain",
            "3 Month WordPress Website",
            "3 Month Business Email"
        ]
    },
    "Wisconsin": {
        stateFee: 135.2,
        agentFee: 49,
        uniqueAddress: 0,
        vykeNumber: 20,
        serviceCharges: 100,
        annualReportFee: 25,
        annualReportDeadline: "End of anniversary quarter",
        stateTaxRate: "7.65%",
        federalTax: "Pass-through",
        additionalRequirements: "Annual report required",
        warnings: ["Annual report required"],
        includes: [
            "USA Number",
            "USA State Verified Registered Agent",
            "Unique address with unique Suite Number",
            "Article of organization",
            "Employer Identification Number (EIN)",
            "Beneficial Ownership Information Report (BOI)",
            "Operating Agreement",
            "1 Year Domain",
            "3 Month WordPress Website",
            "3 Month Business Email"
        ]
    },
    "Wyoming": {
        stateFee: 104,
        agentFee: 25,
        uniqueAddress: 49,
        vykeNumber: 20,
        serviceCharges: 50,
        annualReportFee: 60,
        annualReportDeadline: "Anniversary month",
        stateTaxRate: "0%",
        federalTax: "Pass-through",
        additionalRequirements: "Annual report required",
        warnings: ["Annual report required"],
        recommended: true,
        taxFree: true,
        includes: [
            "USA Number",
            "USA State Verified Registered Agent",
            "Unique address with unique Suite Number",
            "Article of organization",
            "Employer Identification Number (EIN)",
            "Beneficial Ownership Information Report (BOI)",
            "Operating Agreement",
            "1 Year Domain",
            "3 Month WordPress Website",
            "3 Month Business Email"
        ]
    }
};

// C-Corp Formation Data
const corpData = {
    "Alabama": {
        stateFee: 200,
        agentFee: 49,
        uniqueAddress: 0,
        vykeNumber: 20,
        serviceCharges: 250,
        annualFranchiseTax: 0,
        annualReportFee: 0,
        annualReportDeadline: "N/A",
        stateCorpTaxRate: "6.50%",
        federalTax: "21%",
        additionalRequirements: "Business Privilege Tax: $100-15,000 based on net worth",
        warnings: ["Business Privilege Tax based on net worth"],
        includes: [
            "USA Number",
            "USA State Verified Registered Agent",
            "Unique address with unique Suite Number",
            "Certificate of Incorporation / Article of organization",
            "Employer Identification Number (EIN)",
            "Tax Elections",
            "Beneficial Ownership Information Report (BOI)",
            "Shareholder Agreement",
            "1 Year Domain",
            "3 Month WordPress Website",
            "3 Month Business Email"
        ]
    },
    "Alaska": {
        stateFee: 250,
        agentFee: 49,
        uniqueAddress: 0,
        vykeNumber: 20,
        serviceCharges: 250,
        annualFranchiseTax: 0,
        annualReportFee: 100,
        annualReportDeadline: "By Jan 2",
        stateCorpTaxRate: "0-9.4%",
        federalTax: "21%",
        additionalRequirements: "Biennial report every 2 years",
        warnings: ["Biennial report required every 2 years"],
        includes: [
            "USA Number",
            "USA State Verified Registered Agent",
            "Unique address with unique Suite Number",
            "Certificate of Incorporation / Article of organization",
            "Employer Identification Number (EIN)",
            "Tax Elections",
            "Beneficial Ownership Information Report (BOI)",
            "Shareholder Agreement",
            "1 Year Domain",
            "3 Month WordPress Website",
            "3 Month Business Email"
        ]
    },
    "Arizona": {
        stateFee: 130,
        agentFee: 49,
        uniqueAddress: 0,
        vykeNumber: 20,
        serviceCharges: 250,
        annualFranchiseTax: 0,
        annualReportFee: 45,
        annualReportDeadline: "Anniversary date",
        stateCorpTaxRate: "4.90%",
        federalTax: "21%",
        additionalRequirements: "Annual report required",
        warnings: ["Must publish Articles of Incorporation in newspaper for 3 weeks ($50-$500)"],
        includes: [
            "USA Number",
            "USA State Verified Registered Agent",
            "Unique address with unique Suite Number",
            "Certificate of Incorporation / Article of organization",
            "Employer Identification Number (EIN)",
            "Tax Elections",
            "Beneficial Ownership Information Report (BOI)",
            "Shareholder Agreement",
            "1 Year Domain",
            "3 Month WordPress Website",
            "3 Month Business Email"
        ]
    },
    "Arkansas": {
        stateFee: 50,
        agentFee: 49,
        uniqueAddress: 0,
        vykeNumber: 20,
        serviceCharges: 250,
        annualFranchiseTax: 150,
        annualReportFee: 150,
        annualReportDeadline: "1-May",
        stateCorpTaxRate: "1-6.5%",
        federalTax: "21%",
        additionalRequirements: "Franchise Tax based on capital stock",
        warnings: ["Franchise Tax based on capital stock"],
        includes: [
            "USA Number",
            "USA State Verified Registered Agent",
            "Unique address with unique Suite Number",
            "Certificate of Incorporation / Article of organization",
            "Employer Identification Number (EIN)",
            "Tax Elections",
            "Beneficial Ownership Information Report (BOI)",
            "Shareholder Agreement",
            "1 Year Domain",
            "3 Month WordPress Website",
            "3 Month Business Email"
        ]
    },
    "California": {
        stateFee: 100,
        agentFee: 49,
        uniqueAddress: 49,
        vykeNumber: 20,
        serviceCharges: 250,
        annualFranchiseTax: 800,
        annualReportFee: 25,
        annualReportDeadline: "Anniversary month",
        stateCorpTaxRate: "8.84%",
        federalTax: "21%",
        additionalRequirements: "Statement of Information required",
        warnings: [
            "⚠️ HIGH ALERT: $800 minimum franchise tax EVERY YEAR regardless of income",
            "Additional: 8.84% state tax rate (one of highest)",
            "S-Corp Election: Still pays $800 minimum or 1.5% of net income",
            "Penalty: 5.5% per month late penalty on unpaid taxes"
        ],
        highAlert: true,
        includes: [
            "USA Number",
            "USA State Verified Registered Agent",
            "Unique address with unique Suite Number",
            "Certificate of Incorporation / Article of organization",
            "Employer Identification Number (EIN)",
            "Tax Elections",
            "Beneficial Ownership Information Report (BOI)",
            "Shareholder Agreement",
            "1 Year Domain",
            "3 Month WordPress Website",
            "3 Month Business Email"
        ]
    },
    "Colorado": {
        stateFee: 100,
        agentFee: 35,
        uniqueAddress: 0,
        vykeNumber: 20,
        serviceCharges: 250,
        annualFranchiseTax: 0,
        annualReportFee: 10,
        annualReportDeadline: "Anniversary month",
        stateCorpTaxRate: "4.55%",
        federalTax: "21%",
        additionalRequirements: "Periodic report every 2 years",
        warnings: ["Periodic report required every 2 years"],
        includes: [
            "USA Number",
            "USA State Verified Registered Agent",
            "Unique address with unique Suite Number",
            "Certificate of Incorporation / Article of organization",
            "Employer Identification Number (EIN)",
            "Tax Elections",
            "Beneficial Ownership Information Report (BOI)",
            "Shareholder Agreement",
            "1 Year Domain",
            "3 Month WordPress Website",
            "3 Month Business Email"
        ]
    },
    "Connecticut": {
        stateFee: 250,
        agentFee: 49,
        uniqueAddress: 0,
        vykeNumber: 20,
        serviceCharges: 250,
        annualFranchiseTax: 250,
        annualReportFee: 100,
        annualReportDeadline: "Anniversary date",
        stateCorpTaxRate: "7.50%",
        federalTax: "21%",
        additionalRequirements: "Business Entity Tax required",
        warnings: ["Business Entity Tax required"],
        includes: [
            "USA Number",
            "USA State Verified Registered Agent",
            "Unique address with unique Suite Number",
            "Certificate of Incorporation / Article of organization",
            "Employer Identification Number (EIN)",
            "Tax Elections",
            "Beneficial Ownership Information Report (BOI)",
            "Shareholder Agreement",
            "1 Year Domain",
            "3 Month WordPress Website",
            "3 Month Business Email"
        ]
    },
    "Delaware": {
        stateFee: 115,
        agentFee: 29,
        uniqueAddress: 49,
        vykeNumber: 20,
        serviceCharges: 250,
        annualFranchiseTax: 175,
        annualReportFee: 50,
        annualReportDeadline: "1-Mar",
        stateCorpTaxRate: "8.70%",
        federalTax: "21%",
        additionalRequirements: "Franchise tax based on shares/assets",
        warnings: [
            "⚠️ HIGH ALERT: Franchise tax can be $175-$250,000+ based on shares/assets",
            "Choose between Authorized Shares Method or Assumed Par Value Method",
            "Must pay Delaware taxes PLUS home state taxes",
            "Popular for business-friendly courts but expensive"
        ],
        highAlert: true,
        includes: [
            "USA Number",
            "USA State Verified Registered Agent",
            "Unique address with unique Suite Number",
            "Certificate of Incorporation / Article of organization",
            "Employer Identification Number (EIN)",
            "Tax Elections",
            "Beneficial Ownership Information Report (BOI)",
            "Shareholder Agreement",
            "1 Year Domain",
            "3 Month WordPress Website",
            "3 Month Business Email"
        ]
    },
    "Florida": {
        stateFee: 125,
        agentFee: 35,
        uniqueAddress: 49,
        vykeNumber: 20,
        serviceCharges: 250,
        annualFranchiseTax: 0,
        annualReportFee: 150,
        annualReportDeadline: "1-May",
        stateCorpTaxRate: "5.50%",
        federalTax: "21%",
        additionalRequirements: "Annual report required",
        warnings: ["Annual report required"],
        recommended: true,
        taxFree: false,
        includes: [
            "USA Number",
            "USA State Verified Registered Agent",
            "Unique address with unique Suite Number",
            "Certificate of Incorporation / Article of organization",
            "Employer Identification Number (EIN)",
            "Tax Elections",
            "Beneficial Ownership Information Report (BOI)",
            "Shareholder Agreement",
            "1 Year Domain",
            "3 Month WordPress Website",
            "3 Month Business Email"
        ]
    },
    "Georgia": {
        stateFee: 100,
        agentFee: 25,
        uniqueAddress: 49,
        vykeNumber: 20,
        serviceCharges: 250,
        annualFranchiseTax: 0,
        annualReportFee: 50,
        annualReportDeadline: "Between Jan 1-Apr 1",
        stateCorpTaxRate: "5.75%",
        federalTax: "21%",
        additionalRequirements: "Annual registration required",
        warnings: ["Publication requirement varies by county ($40-$100)"],
        includes: [
            "USA Number",
            "USA State Verified Registered Agent",
            "Unique address with unique Suite Number",
            "Certificate of Incorporation / Article of organization",
            "Employer Identification Number (EIN)",
            "Tax Elections",
            "Beneficial Ownership Information Report (BOI)",
            "Shareholder Agreement",
            "1 Year Domain",
            "3 Month WordPress Website",
            "3 Month Business Email"
        ]
    },
    "Hawaii": {
        stateFee: 100,
        agentFee: 49,
        uniqueAddress: 0,
        vykeNumber: 20,
        serviceCharges: 250,
        annualFranchiseTax: 0,
        annualReportFee: 15,
        annualReportDeadline: "Anniversary quarter",
        stateCorpTaxRate: "4.4-6.4%",
        federalTax: "21%",
        additionalRequirements: "Annual report required",
        warnings: ["Annual report required"],
        includes: [
            "USA Number",
            "USA State Verified Registered Agent",
            "Unique address with unique Suite Number",
            "Certificate of Incorporation / Article of organization",
            "Employer Identification Number (EIN)",
            "Tax Elections",
            "Beneficial Ownership Information Report (BOI)",
            "Shareholder Agreement",
            "1 Year Domain",
            "3 Month WordPress Website",
            "3 Month Business Email"
        ]
    },
    "Idaho": {
        stateFee: 120,
        agentFee: 35,
        uniqueAddress: 49,
        vykeNumber: 20,
        serviceCharges: 250,
        annualFranchiseTax: 0,
        annualReportFee: 0,
        annualReportDeadline: "N/A",
        stateCorpTaxRate: "6%",
        federalTax: "21%",
        additionalRequirements: "No annual report required",
        warnings: ["No annual report required - business friendly"],
        includes: [
            "USA Number",
            "USA State Verified Registered Agent",
            "Unique address with unique Suite Number",
            "Certificate of Incorporation / Article of organization",
            "Employer Identification Number (EIN)",
            "Tax Elections",
            "Beneficial Ownership Information Report (BOI)",
            "Shareholder Agreement",
            "1 Year Domain",
            "3 Month WordPress Website",
            "3 Month Business Email"
        ]
    },
    "Illinois": {
        stateFee: 150,
        agentFee: 49,
        uniqueAddress: 49,
        vykeNumber: 20,
        serviceCharges: 250,
        annualFranchiseTax: 75,
        annualReportFee: 75,
        annualReportDeadline: "Anniversary month",
        stateCorpTaxRate: "9.50%",
        federalTax: "21%",
        additionalRequirements: "Franchise tax: 0.1% of paid-in capital",
        warnings: [
            "⚠️ HIGH ALERT: Franchise Tax: 0.1% of paid-in capital ($75 minimum)",
            "Replacement Tax: 2.5% additional tax on corporate income",
            "Combined Rate: Effectively 9.5% total state tax"
        ],
        highAlert: true,
        includes: [
            "USA Number",
            "USA State Verified Registered Agent",
            "Unique address with unique Suite Number",
            "Certificate of Incorporation / Article of organization",
            "Employer Identification Number (EIN)",
            "Tax Elections",
            "Beneficial Ownership Information Report (BOI)",
            "Shareholder Agreement",
            "1 Year Domain",
            "3 Month WordPress Website",
            "3 Month Business Email"
        ]
    },
    "Indiana": {
        stateFee: 90,
        agentFee: 49,
        uniqueAddress: 0,
        vykeNumber: 20,
        serviceCharges: 250,
        annualFranchiseTax: 0,
        annualReportFee: 31,
        annualReportDeadline: "Anniversary month",
        stateCorpTaxRate: "4.90%",
        federalTax: "21%",
        additionalRequirements: "Biennial report every 2 years",
        warnings: ["Biennial report required every 2 years"],
        includes: [
            "USA Number",
            "USA State Verified Registered Agent",
            "Unique address with unique Suite Number",
            "Certificate of Incorporation / Article of organization",
            "Employer Identification Number (EIN)",
            "Tax Elections",
            "Beneficial Ownership Information Report (BOI)",
            "Shareholder Agreement",
            "1 Year Domain",
            "3 Month WordPress Website",
            "3 Month Business Email"
        ]
    },
    "Iowa": {
        stateFee: 50,
        agentFee: 49,
        uniqueAddress: 0,
        vykeNumber: 20,
        serviceCharges: 250,
        annualFranchiseTax: 0,
        annualReportFee: 60,
        annualReportDeadline: "Apr 1 (biennial)",
        stateCorpTaxRate: "5.5-9.8%",
        federalTax: "21%",
        additionalRequirements: "Biennial report every 2 years",
        warnings: ["Biennial report required every 2 years"],
        includes: [
            "USA Number",
            "USA State Verified Registered Agent",
            "Unique address with unique Suite Number",
            "Certificate of Incorporation / Article of organization",
            "Employer Identification Number (EIN)",
            "Tax Elections",
            "Beneficial Ownership Information Report (BOI)",
            "Shareholder Agreement",
            "1 Year Domain",
            "3 Month WordPress Website",
            "3 Month Business Email"
        ]
    },
    "Kansas": {
        stateFee: 90,
        agentFee: 49,
        uniqueAddress: 0,
        vykeNumber: 20,
        serviceCharges: 250,
        annualFranchiseTax: 20,
        annualReportFee: 55,
        annualReportDeadline: "15th day of 4th month",
        stateCorpTaxRate: "4% + 3% surtax",
        federalTax: "21%",
        additionalRequirements: "Annual report required",
        warnings: ["Annual report required"],
        includes: [
            "USA Number",
            "USA State Verified Registered Agent",
            "Unique address with unique Suite Number",
            "Certificate of Incorporation / Article of organization",
            "Employer Identification Number (EIN)",
            "Tax Elections",
            "Beneficial Ownership Information Report (BOI)",
            "Shareholder Agreement",
            "1 Year Domain",
            "3 Month WordPress Website",
            "3 Month Business Email"
        ]
    },
    "Kentucky": {
        stateFee: 50,
        agentFee: 49,
        uniqueAddress: 0,
        vykeNumber: 20,
        serviceCharges: 250,
        annualFranchiseTax: 0,
        annualReportFee: 15,
        annualReportDeadline: "30-Jun",
        stateCorpTaxRate: "5%",
        federalTax: "21%",
        additionalRequirements: "Annual report required",
        warnings: ["Annual report required"],
        includes: [
            "USA Number",
            "USA State Verified Registered Agent",
            "Unique address with unique Suite Number",
            "Certificate of Incorporation / Article of organization",
            "Employer Identification Number (EIN)",
            "Tax Elections",
            "Beneficial Ownership Information Report (BOI)",
            "Shareholder Agreement",
            "1 Year Domain",
            "3 Month WordPress Website",
            "3 Month Business Email"
        ]
    },
    "Louisiana": {
        stateFee: 100,
        agentFee: 49,
        uniqueAddress: 0,
        vykeNumber: 20,
        serviceCharges: 250,
        annualFranchiseTax: 110,
        annualReportFee: 35,
        annualReportDeadline: "Anniversary month",
        stateCorpTaxRate: "4-8%",
        federalTax: "21%",
        additionalRequirements: "Franchise tax: $1.50/$1,000 capital",
        warnings: ["Franchise tax based on capital"],
        includes: [
            "USA Number",
            "USA State Verified Registered Agent",
            "Unique address with unique Suite Number",
            "Certificate of Incorporation / Article of organization",
            "Employer Identification Number (EIN)",
            "Tax Elections",
            "Beneficial Ownership Information Report (BOI)",
            "Shareholder Agreement",
            "1 Year Domain",
            "3 Month WordPress Website",
            "3 Month Business Email"
        ]
    },
    "Maine": {
        stateFee: 145,
        agentFee: 49,
        uniqueAddress: 0,
        vykeNumber: 20,
        serviceCharges: 250,
        annualFranchiseTax: 0,
        annualReportFee: 85,
        annualReportDeadline: "1-Jun",
        stateCorpTaxRate: "3.5-8.93%",
        federalTax: "21%",
        additionalRequirements: "Annual report required",
        warnings: ["Annual report required"],
        includes: [
            "USA Number",
            "USA State Verified Registered Agent",
            "Unique address with unique Suite Number",
            "Certificate of Incorporation / Article of organization",
            "Employer Identification Number (EIN)",
            "Tax Elections",
            "Beneficial Ownership Information Report (BOI)",
            "Shareholder Agreement",
            "1 Year Domain",
            "3 Month WordPress Website",
            "3 Month Business Email"
        ]
    },
    "Maryland": {
        stateFee: 170,
        agentFee: 49,
        uniqueAddress: 0,
        vykeNumber: 20,
        serviceCharges: 250,
        annualFranchiseTax: 0,
        annualReportFee: 300,
        annualReportDeadline: "15-Apr",
        stateCorpTaxRate: "8.25%",
        federalTax: "21%",
        additionalRequirements: "Personal Property Return required",
        warnings: ["Personal Property Return required annually"],
        includes: [
            "USA Number",
            "USA State Verified Registered Agent",
            "Unique address with unique Suite Number",
            "Certificate of Incorporation / Article of organization",
            "Employer Identification Number (EIN)",
            "Tax Elections",
            "Beneficial Ownership Information Report (BOI)",
            "Shareholder Agreement",
            "1 Year Domain",
            "3 Month WordPress Website",
            "3 Month Business Email"
        ]
    },
    "Massachusetts": {
        stateFee: 275,
        agentFee: 49,
        uniqueAddress: 0,
        vykeNumber: 20,
        serviceCharges: 250,
        annualFranchiseTax: 456,
        annualReportFee: 100,
        annualReportDeadline: "Anniversary date",
        stateCorpTaxRate: "8%",
        federalTax: "21%",
        additionalRequirements: "Annual report required",
        warnings: [
            "⚠️ HIGH ALERT: $456 minimum excise tax",
            "Two-part calculation (income + property/payroll)",
            "Rate: 8% on income + 0.26% on tangible property"
        ],
        highAlert: true,
        includes: [
            "USA Number",
            "USA State Verified Registered Agent",
            "Unique address with unique Suite Number",
            "Certificate of Incorporation / Article of organization",
            "Employer Identification Number (EIN)",
            "Tax Elections",
            "Beneficial Ownership Information Report (BOI)",
            "Shareholder Agreement",
            "1 Year Domain",
            "3 Month WordPress Website",
            "3 Month Business Email"
        ]
    },
    "Michigan": {
        stateFee: 60,
        agentFee: 49,
        uniqueAddress: 0,
        vykeNumber: 20,
        serviceCharges: 250,
        annualFranchiseTax: 0,
        annualReportFee: 25,
        annualReportDeadline: "15-May",
        stateCorpTaxRate: "6%",
        federalTax: "21%",
        additionalRequirements: "Annual report required",
        warnings: ["Annual report required"],
        includes: [
            "USA Number",
            "USA State Verified Registered Agent",
            "Unique address with unique Suite Number",
            "Certificate of Incorporation / Article of organization",
            "Employer Identification Number (EIN)",
            "Tax Elections",
            "Beneficial Ownership Information Report (BOI)",
            "Shareholder Agreement",
            "1 Year Domain",
            "3 Month WordPress Website",
            "3 Month Business Email"
        ]
    },
    "Minnesota": {
        stateFee: 135,
        agentFee: 49,
        uniqueAddress: 0,
        vykeNumber: 20,
        serviceCharges: 250,
        annualFranchiseTax: 0,
        annualReportFee: 0,
        annualReportDeadline: "31-Dec",
        stateCorpTaxRate: "9.80%",
        federalTax: "21%",
        additionalRequirements: "Annual renewal required",
        warnings: ["Annual renewal required"],
        includes: [
            "USA Number",
            "USA State Verified Registered Agent",
            "Unique address with unique Suite Number",
            "Certificate of Incorporation / Article of organization",
            "Employer Identification Number (EIN)",
            "Tax Elections",
            "Beneficial Ownership Information Report (BOI)",
            "Shareholder Agreement",
            "1 Year Domain",
            "3 Month WordPress Website",
            "3 Month Business Email"
        ]
    },
    "Mississippi": {
        stateFee: 50,
        agentFee: 49,
        uniqueAddress: 0,
        vykeNumber: 20,
        serviceCharges: 250,
        annualFranchiseTax: 0,
        annualReportFee: 0,
        annualReportDeadline: "15-Apr",
        stateCorpTaxRate: "3-5%",
        federalTax: "21%",
        additionalRequirements: "Annual tax report only",
        warnings: ["Annual tax report only"],
        includes: [
            "USA Number",
            "USA State Verified Registered Agent",
            "Unique address with unique Suite Number",
            "Certificate of Incorporation / Article of organization",
            "Employer Identification Number (EIN)",
            "Tax Elections",
            "Beneficial Ownership Information Report (BOI)",
            "Shareholder Agreement",
            "1 Year Domain",
            "3 Month WordPress Website",
            "3 Month Business Email"
        ]
    },
    "Missouri": {
        stateFee: 105,
        agentFee: 40,
        uniqueAddress: 0,
        vykeNumber: 20,
        serviceCharges: 250,
        annualFranchiseTax: 0,
        annualReportFee: 45,
        annualReportDeadline: "Anniversary month",
        stateCorpTaxRate: "4%",
        federalTax: "21%",
        additionalRequirements: "Annual registration required",
        warnings: ["Annual registration required"],
        includes: [
            "USA Number",
            "USA State Verified Registered Agent",
            "Unique address with unique Suite Number",
            "Certificate of Incorporation / Article of organization",
            "Employer Identification Number (EIN)",
            "Tax Elections",
            "Beneficial Ownership Information Report (BOI)",
            "Shareholder Agreement",
            "1 Year Domain",
            "3 Month WordPress Website",
            "3 Month Business Email"
        ]
    },
    "Montana": {
        stateFee: 70,
        agentFee: 45,
        uniqueAddress: 49,
        vykeNumber: 20,
        serviceCharges: 250,
        annualFranchiseTax: 50,
        annualReportFee: 20,
        annualReportDeadline: "15-Apr",
        stateCorpTaxRate: "6.75%",
        federalTax: "21%",
        additionalRequirements: "Annual report required",
        warnings: ["Annual report required"],
        recommended: true,
        taxFree: false,
        includes: [
            "USA Number",
            "USA State Verified Registered Agent",
            "Unique address with unique Suite Number",
            "Certificate of Incorporation / Article of organization",
            "Employer Identification Number (EIN)",
            "Tax Elections",
            "Beneficial Ownership Information Report (BOI)",
            "Shareholder Agreement",
            "1 Year Domain",
            "3 Month WordPress Website",
            "3 Month Business Email"
        ]
    },
    "Nebraska": {
        stateFee: 100,
        agentFee: 49,
        uniqueAddress: 0,
        vykeNumber: 20,
        serviceCharges: 250,
        annualFranchiseTax: 0,
        annualReportFee: 26,
        annualReportDeadline: "Apr 1 (biennial)",
        stateCorpTaxRate: "5.58-7.81%",
        federalTax: "21%",
        additionalRequirements: "Biennial report every 2 years",
        warnings: ["Biennial report required every 2 years"],
        includes: [
            "USA Number",
            "USA State Verified Registered Agent",
            "Unique address with unique Suite Number",
            "Certificate of Incorporation / Article of organization",
            "Employer Identification Number (EIN)",
            "Tax Elections",
            "Beneficial Ownership Information Report (BOI)",
            "Shareholder Agreement",
            "1 Year Domain",
            "3 Month WordPress Website",
            "3 Month Business Email"
        ]
    },
    "Nevada": {
        stateFee: 425,
        agentFee: 35,
        uniqueAddress: 49,
        vykeNumber: 20,
        serviceCharges: 250,
        annualFranchiseTax: 0,
        annualReportFee: 150,
        annualReportDeadline: "End of anniversary month",
        stateCorpTaxRate: "0%",
        federalTax: "21%",
        additionalRequirements: "Annual List, Business License: $500",
        warnings: ["Business License fee of $500 annually"],
        taxFree: true,
        includes: [
            "USA Number",
            "USA State Verified Registered Agent",
            "Unique address with unique Suite Number",
            "Certificate of Incorporation / Article of organization",
            "Employer Identification Number (EIN)",
            "Tax Elections",
            "Beneficial Ownership Information Report (BOI)",
            "Shareholder Agreement",
            "1 Year Domain",
            "3 Month WordPress Website",
            "3 Month Business Email"
        ]
    },
    "New Hampshire": {
        stateFee: 100,
        agentFee: 49,
        uniqueAddress: 0,
        vykeNumber: 20,
        serviceCharges: 250,
        annualFranchiseTax: 0,
        annualReportFee: 100,
        annualReportDeadline: "1-Apr",
        stateCorpTaxRate: "7.70%",
        federalTax: "21%",
        additionalRequirements: "Annual report required",
        warnings: ["Annual report required"],
        includes: [
            "USA Number",
            "USA State Verified Registered Agent",
            "Unique address with unique Suite Number",
            "Certificate of Incorporation / Article of organization",
            "Employer Identification Number (EIN)",
            "Tax Elections",
            "Beneficial Ownership Information Report (BOI)",
            "Shareholder Agreement",
            "1 Year Domain",
            "3 Month WordPress Website",
            "3 Month Business Email"
        ]
    },
    "New Jersey": {
        stateFee: 125,
        agentFee: 49,
        uniqueAddress: 0,
        vykeNumber: 20,
        serviceCharges: 250,
        annualFranchiseTax: 500,
        annualReportFee: 75,
        annualReportDeadline: "Anniversary month",
        stateCorpTaxRate: "9%",
        federalTax: "21%",
        additionalRequirements: "Annual report required",
        warnings: ["Annual report required"],
        includes: [
            "USA Number",
            "USA State Verified Registered Agent",
            "Unique address with unique Suite Number",
            "Certificate of Incorporation / Article of organization",
            "Employer Identification Number (EIN)",
            "Tax Elections",
            "Beneficial Ownership Information Report (BOI)",
            "Shareholder Agreement",
            "1 Year Domain",
            "3 Month WordPress Website",
            "3 Month Business Email"
        ]
    },
    "New Mexico": {
        stateFee: 100,
        agentFee: 35,
        uniqueAddress: 49,
        vykeNumber: 20,
        serviceCharges: 250,
        annualFranchiseTax: 50,
        annualReportFee: 25,
        annualReportDeadline: "15th day of 5th month",
        stateCorpTaxRate: "4.8-5.9%",
        federalTax: "21%",
        additionalRequirements: "Annual report required",
        warnings: ["Annual report required"],
        includes: [
            "USA Number",
            "USA State Verified Registered Agent",
            "Unique address with unique Suite Number",
            "Certificate of Incorporation / Article of organization",
            "Employer Identification Number (EIN)",
            "Tax Elections",
            "Beneficial Ownership Information Report (BOI)",
            "Shareholder Agreement",
            "1 Year Domain",
            "3 Month WordPress Website",
            "3 Month Business Email"
        ]
    },
    "New York": {
        stateFee: 575,
        agentFee: 49,
        uniqueAddress: 49,
        vykeNumber: 20,
        serviceCharges: 250,
        annualFranchiseTax: 25,
        annualReportFee: 9,
        annualReportDeadline: "Anniversary month",
        stateCorpTaxRate: "6.50%",
        federalTax: "21%",
        additionalRequirements: "MTA surcharge if in NYC area",
        warnings: [
            "⚠️ HIGH ALERT: Complex tax structure with multiple taxes",
            "MTA Surcharge: Additional tax if in NYC metropolitan area",
            "Fixed Dollar Minimum: $25-$5,000 based on receipts",
            "Combined Reporting: Must include all related entities"
        ],
        highAlert: true,
        includes: [
            "USA Number",
            "USA State Verified Registered Agent",
            "Unique address with unique Suite Number",
            "Certificate of Incorporation / Article of organization",
            "Employer Identification Number (EIN)",
            "Tax Elections",
            "Beneficial Ownership Information Report (BOI)",
            "Shareholder Agreement",
            "1 Year Domain",
            "3 Month WordPress Website",
            "3 Month Business Email"
        ]
    },
    "North Carolina": {
        stateFee: 125,
        agentFee: 49,
        uniqueAddress: 0,
        vykeNumber: 20,
        serviceCharges: 250,
        annualFranchiseTax: 0,
        annualReportFee: 200,
        annualReportDeadline: "15th day of 4th month",
        stateCorpTaxRate: "2.50%",
        federalTax: "21%",
        additionalRequirements: "Annual report required",
        warnings: ["Annual report required"],
        includes: [
            "USA Number",
            "USA State Verified Registered Agent",
            "Unique address with unique Suite Number",
            "Certificate of Incorporation / Article of organization",
            "Employer Identification Number (EIN)",
            "Tax Elections",
            "Beneficial Ownership Information Report (BOI)",
            "Shareholder Agreement",
            "1 Year Domain",
            "3 Month WordPress Website",
            "3 Month Business Email"
        ]
    },
    "North Dakota": {
        stateFee: 100,
        agentFee: 30,
        uniqueAddress: 0,
        vykeNumber: 20,
        serviceCharges: 250,
        annualFranchiseTax: 0,
        annualReportFee: 25,
        annualReportDeadline: "1-Aug",
        stateCorpTaxRate: "1.41-4.31%",
        federalTax: "21%",
        additionalRequirements: "Annual report required",
        warnings: ["Annual report required"],
        includes: [
            "USA Number",
            "USA State Verified Registered Agent",
            "Unique address with unique Suite Number",
            "Certificate of Incorporation / Article of organization",
            "Employer Identification Number (EIN)",
            "Tax Elections",
            "Beneficial Ownership Information Report (BOI)",
            "Shareholder Agreement",
            "1 Year Domain",
            "3 Month WordPress Website",
            "3 Month Business Email"
        ]
    },
    "Ohio": {
        stateFee: 99,
        agentFee: 49,
        uniqueAddress: 0,
        vykeNumber: 20,
        serviceCharges: 250,
        annualFranchiseTax: 0,
        annualReportFee: 0,
        annualReportDeadline: "N/A",
        stateCorpTaxRate: "0%",
        federalTax: "21%",
        additionalRequirements: "CAT tax: 0.26% gross receipts",
        warnings: ["CAT tax applies to gross receipts"],
        taxFree: true,
        includes: [
            "USA Number",
            "USA State Verified Registered Agent",
            "Unique address with unique Suite Number",
            "Certificate of Incorporation / Article of organization",
            "Employer Identification Number (EIN)",
            "Tax Elections",
            "Beneficial Ownership Information Report (BOI)",
            "Shareholder Agreement",
            "1 Year Domain",
            "3 Month WordPress Website",
            "3 Month Business Email"
        ]
    },
    "Oklahoma": {
        stateFee: 100,
        agentFee: 49,
        uniqueAddress: 0,
        vykeNumber: 20,
        serviceCharges: 250,
        annualFranchiseTax: 0,
        annualReportFee: 25,
        annualReportDeadline: "Anniversary month",
        stateCorpTaxRate: "6%",
        federalTax: "21%",
        additionalRequirements: "Annual certificate required",
        warnings: ["Annual certificate required"],
        includes: [
            "USA Number",
            "USA State Verified Registered Agent",
            "Unique address with unique Suite Number",
            "Certificate of Incorporation / Article of organization",
            "Employer Identification Number (EIN)",
            "Tax Elections",
            "Beneficial Ownership Information Report (BOI)",
            "Shareholder Agreement",
            "1 Year Domain",
            "3 Month WordPress Website",
            "3 Month Business Email"
        ]
    },
    "Oregon": {
        stateFee: 100,
        agentFee: 35,
        uniqueAddress: 49,
        vykeNumber: 20,
        serviceCharges: 250,
        annualFranchiseTax: 150,
        annualReportFee: 100,
        annualReportDeadline: "Anniversary date",
        stateCorpTaxRate: "6.6-7.6%",
        federalTax: "21%",
        additionalRequirements: "Annual report required",
        warnings: ["Annual report required"],
        includes: [
            "USA Number",
            "USA State Verified Registered Agent",
            "Unique address with unique Suite Number",
            "Certificate of Incorporation / Article of organization",
            "Employer Identification Number (EIN)",
            "Tax Elections",
            "Beneficial Ownership Information Report (BOI)",
            "Shareholder Agreement",
            "1 Year Domain",
            "3 Month WordPress Website",
            "3 Month Business Email"
        ]
    },
    "Pennsylvania": {
        stateFee: 125,
        agentFee: 49,
        uniqueAddress: 0,
        vykeNumber: 20,
        serviceCharges: 250,
        annualFranchiseTax: 0,
        annualReportFee: 70,
        annualReportDeadline: "15-Apr",
        stateCorpTaxRate: "9.99%",
        federalTax: "21%",
        additionalRequirements: "Annual report required",
        warnings: ["Must advertise incorporation in 2 newspapers ($200-$500)"],
        includes: [
            "USA Number",
            "USA State Verified Registered Agent",
            "Unique address with unique Suite Number",
            "Certificate of Incorporation / Article of organization",
            "Employer Identification Number (EIN)",
            "Tax Elections",
            "Beneficial Ownership Information Report (BOI)",
            "Shareholder Agreement",
            "1 Year Domain",
            "3 Month WordPress Website",
            "3 Month Business Email"
        ]
    },
    "Rhode Island": {
        stateFee: 230,
        agentFee: 49,
        uniqueAddress: 0,
        vykeNumber: 20,
        serviceCharges: 250,
        annualFranchiseTax: 500,
        annualReportFee: 50,
        annualReportDeadline: "Anniversary month",
        stateCorpTaxRate: "7%",
        federalTax: "21%",
        additionalRequirements: "Annual report required",
        warnings: ["Annual report required"],
        includes: [
            "USA Number",
            "USA State Verified Registered Agent",
            "Unique address with unique Suite Number",
            "Certificate of Incorporation / Article of organization",
            "Employer Identification Number (EIN)",
            "Tax Elections",
            "Beneficial Ownership Information Report (BOI)",
            "Shareholder Agreement",
            "1 Year Domain",
            "3 Month WordPress Website",
            "3 Month Business Email"
        ]
    },
    "South Carolina": {
        stateFee: 110,
        agentFee: 49,
        uniqueAddress: 0,
        vykeNumber: 20,
        serviceCharges: 250,
        annualFranchiseTax: 0,
        annualReportFee: 0,
        annualReportDeadline: "N/A",
        stateCorpTaxRate: "5%",
        federalTax: "21%",
        additionalRequirements: "Annual tax filing only",
        warnings: ["Annual tax filing only"],
        includes: [
            "USA Number",
            "USA State Verified Registered Agent",
            "Unique address with unique Suite Number",
            "Certificate of Incorporation / Article of organization",
            "Employer Identification Number (EIN)",
            "Tax Elections",
            "Beneficial Ownership Information Report (BOI)",
            "Shareholder Agreement",
            "1 Year Domain",
            "3 Month WordPress Website",
            "3 Month Business Email"
        ]
    },
    "South Dakota": {
        stateFee: 150,
        agentFee: 49,
        uniqueAddress: 0,
        vykeNumber: 20,
        serviceCharges: 250,
        annualFranchiseTax: 0,
        annualReportFee: 50,
        annualReportDeadline: "Anniversary month",
        stateCorpTaxRate: "0%",
        federalTax: "21%",
        additionalRequirements: "Annual report required",
        warnings: ["Annual report required"],
        taxFree: true,
        includes: [
            "USA Number",
            "USA State Verified Registered Agent",
            "Unique address with unique Suite Number",
            "Certificate of Incorporation / Article of organization",
            "Employer Identification Number (EIN)",
            "Tax Elections",
            "Beneficial Ownership Information Report (BOI)",
            "Shareholder Agreement",
            "1 Year Domain",
            "3 Month WordPress Website",
            "3 Month Business Email"
        ]
    },
    "Tennessee": {
        stateFee: 100,
        agentFee: 49,
        uniqueAddress: 0,
        vykeNumber: 20,
        serviceCharges: 250,
        annualFranchiseTax: 100,
        annualReportFee: 20,
        annualReportDeadline: "15th day of 4th month",
        stateCorpTaxRate: "6.50%",
        federalTax: "21%",
        additionalRequirements: "Franchise & Excise Tax required",
        warnings: [
            "⚠️ HIGH ALERT: Franchise Tax: $0.25 per $100 of net worth",
            "Excise Tax: 6.5% on net earnings",
            "Combined filing required"
        ],
        highAlert: true,
        includes: [
            "USA Number",
            "USA State Verified Registered Agent",
            "Unique address with unique Suite Number",
            "Certificate of Incorporation / Article of organization",
            "Employer Identification Number (EIN)",
            "Tax Elections",
            "Beneficial Ownership Information Report (BOI)",
            "Shareholder Agreement",
            "1 Year Domain",
            "3 Month WordPress Website",
            "3 Month Business Email"
        ]
    },
    "Texas": {
        stateFee: 310,
        agentFee: 35,
        uniqueAddress: 49,
        vykeNumber: 20,
        serviceCharges: 250,
        annualFranchiseTax: 0,
        annualReportFee: 0,
        annualReportDeadline: "15-May",
        stateCorpTaxRate: "0%",
        federalTax: "21%",
        additionalRequirements: "Franchise Tax: 0.75% gross receipts",
        warnings: ["Franchise Tax: 0.75% on gross receipts over $1.23 million"],
        recommended: true,
        taxFree: true,
        includes: [
            "USA Number",
            "USA State Verified Registered Agent",
            "Unique address with unique Suite Number",
            "Certificate of Incorporation / Article of organization",
            "Employer Identification Number (EIN)",
            "Tax Elections",
            "Beneficial Ownership Information Report (BOI)",
            "Shareholder Agreement",
            "1 Year Domain",
            "3 Month WordPress Website",
            "3 Month Business Email"
        ]
    },
    "Utah": {
        stateFee: 70,
        agentFee: 49,
        uniqueAddress: 49,
        vykeNumber: 20,
        serviceCharges: 250,
        annualFranchiseTax: 100,
        annualReportFee: 20,
        annualReportDeadline: "Anniversary month",
        stateCorpTaxRate: "4.95%",
        federalTax: "21%",
        additionalRequirements: "Annual renewal required",
        warnings: ["Annual renewal required"],
        includes: [
            "USA Number",
            "USA State Verified Registered Agent",
            "Unique address with unique Suite Number",
            "Certificate of Incorporation / Article of organization",
            "Employer Identification Number (EIN)",
            "Tax Elections",
            "Beneficial Ownership Information Report (BOI)",
            "Shareholder Agreement",
            "1 Year Domain",
            "3 Month WordPress Website",
            "3 Month Business Email"
        ]
    },
    "Vermont": {
        stateFee: 125,
        agentFee: 49,
        uniqueAddress: 0,
        vykeNumber: 20,
        serviceCharges: 250,
        annualFranchiseTax: 250,
        annualReportFee: 35,
        annualReportDeadline: "Anniversary month",
        stateCorpTaxRate: "6-8.5%",
        federalTax: "21%",
        additionalRequirements: "Annual report required",
        warnings: ["Annual report required"],
        includes: [
            "USA Number",
            "USA State Verified Registered Agent",
            "Unique address with unique Suite Number",
            "Certificate of Incorporation / Article of organization",
            "Employer Identification Number (EIN)",
            "Tax Elections",
            "Beneficial Ownership Information Report (BOI)",
            "Shareholder Agreement",
            "1 Year Domain",
            "3 Month WordPress Website",
            "3 Month Business Email"
        ]
    },
    "Virginia": {
        stateFee: 75,
        agentFee: 49,
        uniqueAddress: 49,
        vykeNumber: 20,
        serviceCharges: 250,
        annualFranchiseTax: 0,
        annualReportFee: 100,
        annualReportDeadline: "Last day of anniversary month",
        stateCorpTaxRate: "6%",
        federalTax: "21%",
        additionalRequirements: "Annual registration required",
        warnings: ["Annual registration required"],
        includes: [
            "USA Number",
            "USA State Verified Registered Agent",
            "Unique address with unique Suite Number",
            "Certificate of Incorporation / Article of organization",
            "Employer Identification Number (EIN)",
            "Tax Elections",
            "Beneficial Ownership Information Report (BOI)",
            "Shareholder Agreement",
            "1 Year Domain",
            "3 Month WordPress Website",
            "3 Month Business Email"
        ]
    },
    "Washington": {
        stateFee: 200,
        agentFee: 59,
        uniqueAddress: 49,
        vykeNumber: 20,
        serviceCharges: 250,
        annualFranchiseTax: 0,
        annualReportFee: 60,
        annualReportDeadline: "End of anniversary month",
        stateCorpTaxRate: "0%",
        federalTax: "21%",
        additionalRequirements: "B&O Tax: 0.471-1.75% gross receipts",
        warnings: ["B&O Tax applies to gross receipts"],
        taxFree: true,
        includes: [
            "USA Number",
            "USA State Verified Registered Agent",
            "Unique address with unique Suite Number",
            "Certificate of Incorporation / Article of organization",
            "Employer Identification Number (EIN)",
            "Tax Elections",
            "Beneficial Ownership Information Report (BOI)",
            "Shareholder Agreement",
            "1 Year Domain",
            "3 Month WordPress Website",
            "3 Month Business Email"
        ]
    },
    "West Virginia": {
        stateFee: 100,
        agentFee: 49,
        uniqueAddress: 0,
        vykeNumber: 20,
        serviceCharges: 250,
        annualFranchiseTax: 0,
        annualReportFee: 25,
        annualReportDeadline: "30-Jun",
        stateCorpTaxRate: "6.50%",
        federalTax: "21%",
        additionalRequirements: "Annual report required",
        warnings: ["Annual report required"],
        includes: [
            "USA Number",
            "USA State Verified Registered Agent",
            "Unique address with unique Suite Number",
            "Certificate of Incorporation / Article of organization",
            "Employer Identification Number (EIN)",
            "Tax Elections",
            "Beneficial Ownership Information Report (BOI)",
            "Shareholder Agreement",
            "1 Year Domain",
            "3 Month WordPress Website",
            "3 Month Business Email"
        ]
    },
    "Wisconsin": {
        stateFee: 100,
        agentFee: 49,
        uniqueAddress: 0,
        vykeNumber: 20,
        serviceCharges: 250,
        annualFranchiseTax: 25,
        annualReportFee: 40,
        annualReportDeadline: "End of anniversary quarter",
        stateCorpTaxRate: "7.90%",
        federalTax: "21%",
        additionalRequirements: "Annual report required",
        warnings: ["Annual report required"],
        includes: [
            "USA Number",
            "USA State Verified Registered Agent",
            "Unique address with unique Suite Number",
            "Certificate of Incorporation / Article of organization",
            "Employer Identification Number (EIN)",
            "Tax Elections",
            "Beneficial Ownership Information Report (BOI)",
            "Shareholder Agreement",
            "1 Year Domain",
            "3 Month WordPress Website",
            "3 Month Business Email"
        ]
    },
    "Wyoming": {
        stateFee: 104,
        agentFee: 25,
        uniqueAddress: 49,
        vykeNumber: 20,
        serviceCharges: 250,
        annualFranchiseTax: 60,
        annualReportFee: 60,
        annualReportDeadline: "Anniversary month",
        stateCorpTaxRate: "0%",
        federalTax: "21%",
        additionalRequirements: "Annual report required",
        warnings: ["Annual report required"],
        recommended: true,
        taxFree: true,
        includes: [
            "USA Number",
            "USA State Verified Registered Agent",
            "Unique address with unique Suite Number",
            "Certificate of Incorporation / Article of organization",
            "Employer Identification Number (EIN)",
            "Tax Elections",
            "Beneficial Ownership Information Report (BOI)",
            "Shareholder Agreement",
            "1 Year Domain",
            "3 Month WordPress Website",
            "3 Month Business Email"
        ]
    }
};

// Export data for use in other files
window.llcData = llcData;
window.corpData = corpData;
